const KEYS={products:"gyx_products_v1",orders:"gyx_orders_v1",settings:"gyx_settings_v1"};
const defaults={settings:{name:"全球优选",telegram:"https://t.me/your_username",network:"USDT-TRC20",wallet:"请在管理后台填写真实TRC20地址",minutes:15},products:[]};
const $=id=>document.getElementById(id);
function getData(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function saveData(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
let products=getData(KEYS.products,[]),orders=getData(KEYS.orders,[]),settings=getData(KEYS.settings,defaults.settings);
function showPanel(name){document.querySelectorAll(".admin-panel").forEach(p=>p.classList.add("hidden"));$(name+"Panel").classList.remove("hidden");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.panel===name));if(name==="dashboard")renderStats();if(name==="products")renderProducts();if(name==="orders")renderOrders();if(name==="settings")loadSettings()}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));
function renderStats(){products=getData(KEYS.products,[]);orders=getData(KEYS.orders,[]);const paid=orders.filter(o=>o.status==="paid");const revenue=paid.reduce((a,o)=>a+Number(o.amount),0);$("statsGrid").innerHTML=[["商品数量",products.length],["订单总数",orders.length],["已付款订单",paid.length],["销售额",revenue.toFixed(3)+" USDT"]].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("")}
function renderProducts(){products=getData(KEYS.products,[]);$("adminProductList").innerHTML=products.length?products.map(p=>`<div class="admin-row"><div><h3>${esc(p.emoji||"📦")} ${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="meta"><span>${esc(p.category||"其他")}</span><span>${Number(p.price).toFixed(2)} USDT</span><span>${p.stockType==="unlimited"?"无限库存":"库存 "+p.stock}</span><span>${p.active?"已上架":"已下架"}</span></div></div><div class="row-actions"><button class="ghost" onclick="editProduct('${p.id}')">编辑</button><button class="danger" onclick="deleteProduct('${p.id}')">删除</button></div></div>`).join(""):`<div class="admin-card">暂无商品</div>`}
function openEdit(p=null){$("editTitle").textContent=p?"编辑商品":"新增商品";$("editId").value=p?.id||"";$("editName").value=p?.name||"";$("editDesc").value=p?.desc||"";$("editPrice").value=p?.price??0;$("editCategory").value=p?.category||"";$("editEmoji").value=p?.emoji||"📦";$("editDeliveryType").value=p?.deliveryType||"download";$("editDelivery").value=p?.delivery||"";$("editStockType").value=p?.stockType||"unlimited";$("editStock").value=p?.stock??9999;$("editActive").checked=p?.active??true;$("productEditModal").classList.remove("hidden")}
window.editProduct=id=>{products=getData(KEYS.products,[]);openEdit(products.find(p=>p.id===id))}
window.deleteProduct=id=>{if(!confirm("确定删除这个商品吗？"))return;products=getData(KEYS.products,[]).filter(p=>p.id!==id);saveData(KEYS.products,products);renderProducts();renderStats()}
function saveProduct(){const name=$("editName").value.trim(),desc=$("editDesc").value.trim();if(!name||!desc){alert("请填写商品名称和介绍");return}products=getData(KEYS.products,[]);const data={id:$("editId").value||"p"+Date.now(),name,desc,price:Number($("editPrice").value||0),category:$("editCategory").value.trim()||"其他",emoji:$("editEmoji").value.trim()||"📦",deliveryType:$("editDeliveryType").value,delivery:$("editDelivery").value.trim(),stockType:$("editStockType").value,stock:Number($("editStock").value||0),active:$("editActive").checked};const i=products.findIndex(p=>p.id===data.id);if(i>=0)products[i]=data;else products.unshift(data);saveData(KEYS.products,products);$("productEditModal").classList.add("hidden");renderProducts();renderStats()}
function renderOrders(){orders=getData(KEYS.orders,[]);const map={waiting:"等待付款",paid:"已付款",expired:"已过期"};$("adminOrderList").innerHTML=orders.length?orders.map(o=>`<div class="admin-row"><div><h3>${esc(o.productName)}</h3><p>订单号：${esc(o.id)}<br>邮箱：${esc(o.email)}<br>金额：${esc(o.amount)} USDT</p><div class="meta"><span class="status-${o.status}">${map[o.status]||o.status}</span><span>${new Date(o.createdAt).toLocaleString()}</span></div></div><div class="row-actions">${o.status==="waiting"?`<button class="primary" onclick="markPaid('${o.id}')">标记已付款</button>`:""}</div></div>`).join(""):`<div class="admin-card">暂无订单</div>`}
window.markPaid=id=>{orders=getData(KEYS.orders,[]);const i=orders.findIndex(o=>o.id===id);if(i>=0){orders[i].status="paid";orders[i].updatedAt=new Date().toISOString();saveData(KEYS.orders,orders);renderOrders();renderStats()}}
function loadSettings(){settings=getData(KEYS.settings,defaults.settings);$("settingName").value=settings.name;$("settingTelegram").value=settings.telegram;$("settingNetwork").value=settings.network;$("settingWallet").value=settings.wallet;$("settingMinutes").value=settings.minutes}
$("settingsForm").onsubmit=e=>{e.preventDefault();settings={name:$("settingName").value.trim()||"全球优选",telegram:$("settingTelegram").value.trim(),network:$("settingNetwork").value,wallet:$("settingWallet").value.trim(),minutes:Number($("settingMinutes").value||15)};saveData(KEYS.settings,settings);alert("设置已保存")};
$("addProductBtn").onclick=()=>openEdit();$("saveProductBtn").onclick=saveProduct;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add("hidden"));$("productEditModal").onclick=e=>{if(e.target===$("productEditModal"))$("productEditModal").classList.add("hidden")};renderStats();