(() => {
  'use strict';
  // Search-only controller. Keep UI/order/payment/theme untouched.
  const db = window.gyxSupabase;
  const i18n = window.GYXI18N;
  if (!db || !i18n) return;
  const $ = (id) => document.getElementById(id);
  const form=$('problemForm'), input=$('problemInput'), searchBtn=$('startMatchButton'), problemMessage=$('problemMessage');
  const quizPanel=$('quizPanel'), resultPanel=$('resultPanel'), stepEl=$('quizStepLabel'), progressEl=$('quizProgressBar');
  const originalEl=$('originalQuestion'), questionEl=$('quizQuestion'), helpEl=$('quizHelp'), optionsEl=$('quizOptions');
  const backBtn=$('quizBackButton'), restartBtn=$('restartMatchButton');
  if (!form||!input||!quizPanel||!optionsEl) return;
  const MATCH_STORAGE_KEY='gyx_pending_answer_match';
  const TIER_PRODUCTS={essential:'answer-essential',standard:'answer-standard',detailed:'answer-detailed',professional:'answer-professional',custom:'answer-custom'};
  let answers=[],products=[],dataReady=false,originalQuestion='',history=[],round=0,firstCandidates=[],firstSelectedId=null,busy=false,runId=0,idleTimer=null,composing=false,typingToken=0;
  const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
  const locale=()=>i18n.locale||'zh-CN';
  const title=a=>locale()==='en'?(a.title_en||a.title||''):locale()==='km'?(a.title_km||a.title||''):(a.title||'');
  const summary=a=>locale()==='en'?(a.answer_summary_en||a.answer_summary||''):locale()==='km'?(a.answer_summary_km||a.answer_summary||''):(a.answer_summary||'');
  function msg(t,k='success'){if(!problemMessage)return;problemMessage.textContent=t||'';problemMessage.className=t?('form-message show '+k):'form-message';}
  async function loadData(){if(dataReady)return true;const [ar,pr]=await Promise.all([db.from('product_answer_options').select('id,answer_code,module_code,title,title_en,title_km,answer_summary,answer_summary_en,answer_summary_km,keywords,priority').eq('is_active',true).order('priority',{ascending:false}).limit(500),db.from('products').select('id,product_name,product_price,currency,description').eq('is_active',true)]);if(ar.error||pr.error)return false;answers=ar.data||[];products=pr.data||[];dataReady=answers.length>0;return dataReady;}
  function toks(v){const s=clean(v).toLowerCase().normalize('NFKC'),o=new Set();(s.match(/[a-z0-9]{2,}/g)||[]).forEach(x=>o.add(x));(s.match(/[\u3400-\u9fff]{2,}/g)||[]).forEach(seg=>{for(let n=2;n<=Math.min(4,seg.length);n++)for(let i=0;i<=seg.length-n;i++)o.add(seg.slice(i,i+n));});return [...o].slice(0,100);}
  function score(a,q){const ti=[a.title,a.title_en,a.title_km].filter(Boolean).join(' ').toLowerCase(),su=[a.answer_summary,a.answer_summary_en,a.answer_summary_km].filter(Boolean).join(' ').toLowerCase(),kw=(Array.isArray(a.keywords)?a.keywords.join(' '):String(a.keywords||'')).toLowerCase(),text=ti+' '+su+' '+kw;let s=0;const qq=clean(q).toLowerCase();if(text.includes(qq))s+=40;if(ti.includes(qq))s+=20;toks(q).forEach(x=>{if(ti.includes(x))s+=8;if(kw.includes(x))s+=6;if(su.includes(x))s+=2;});return s+Math.min(5,Number(a.priority||0)/20);}
  function domainText(){return (originalQuestion+' '+history.map(x=>x.label).join(' ')).toLowerCase();}
  function contextual(n){const t=domainText(),last=history.at(-1)?.label||originalQuestion;
    if(/装修|酒店|店铺|门店|效果图|做图|空间设计/.test(t)){const s={2:['客房/套房效果图','大堂/前台效果图','餐厅/公共区域效果图','平面布局与动线图','整套酒店空间效果图'],3:['只有现场照片','已有平面图/尺寸','已有参考风格图','已有草图需要优化','从零开始没有设计资料'],4:['先确定空间布局','先确定装修风格','控制装修预算成本','解决采光/动线问题','直接生成可参考效果图'],5:['可直接复制的AI出图提示词','手机从照片到效果图步骤','酒店空间设计与出图流程','多空间多角度效果图方案','从布局到效果图完整执行方案']};return{question:n===2?'你具体要做酒店哪一部分的图？':n===3?`做“${last}”，你现在手里有什么资料？`:n===4?`基于“${last}”，你现在最需要先解决什么？`:`最后确认：你希望拿到哪种能直接使用的结果？`,options:s[n]};}
    if(/宠物|猫|狗|养护|喂养/.test(t)){const s={2:['猫咪日常养护','狗狗日常养护','幼宠喂养护理','成年宠物健康管理','老年宠物专项护理'],3:['饮食与营养搭配','清洁洗护与毛发','行为训练与习惯','疫苗驱虫与健康观察','已有具体异常需要排查'],4:['从零建立养护习惯','解决当前具体问题','降低长期养护成本','制定每日每周计划','提高宠物健康稳定性'],5:['日常养护清单','喂养护理步骤','具体问题排查方案','长期健康管理计划','针对当前情况的完整方案']};return{question:n===2?'你主要想解决哪类宠物养护？':n===3?`围绕“${last}”，你最关心哪一块？`:n===4?`针对“${last}”，当前最优先的目标是什么？`:'最后确认：你希望这份资料直接帮你完成什么？',options:s[n]};}
    if(/赚钱|副业|兼职|收入|变现/.test(t)){const s={2:['用现有技能接单赚钱','用AI做内容/设计服务','做商品推广或电商','做本地服务获客','从零找低门槛副业'],3:['只有手机和少量时间','每天可投入1到2小时','有技能但没有客户','有账号/流量但不会变现','完全从零没有资源'],4:['先赚到第一笔收入','找到真实客户来源','提高成交率和客单价','把重复工作交给AI','形成稳定可复制流程'],5:['今天就能执行的步骤','免费工具与操作方法','获客到成交完整路径','AI辅助执行模板','长期可复制副业方案']};return{question:n===2?'你更想通过哪种方式赚钱？':n===3?`选择“${last}”后，你现在最接近哪种条件？`:n===4?`在“${last}”这条路上，你最先要解决什么？`:'最后确认：你最希望拿到哪种可执行结果？',options:s[n]};}
    const base={2:[`明确“${last}”具体对象`,`确定“${last}”使用场景`,`选择“${last}”实现方式`,`解决“${last}”当前难点`,`直接完成“${last}”`],3:[`从零开始做“${last}”`,`已有资料继续做“${last}”`,`已有工具但不会操作`,`做过但效果不好`,`需要提高效率和质量`],4:['先解决最关键问题','需要一步一步操作','需要可复制模板','需要完整执行流程','需要针对当前情况优化'],5:['最快完成一次','解决当前具体问题','提高结果质量','形成可重复流程','获得完整系统方案']};return{question:`围绕“${last}”，下一步你最需要哪一种？`,options:base[n]};}
  }
  function setRound(n,q=''){round=n;stepEl.textContent=`第 ${n} / 5 轮`;if(progressEl)progressEl.style.width=`${n*20}%`;if(originalEl)originalEl.textContent=`“${originalQuestion}”`;questionEl.textContent=q;if(helpEl)helpEl.textContent='';if(backBtn)backBtn.classList.toggle('hidden',n===1);}
  function clear(){optionsEl.replaceChildren();}
  function typeInto(el,text,speed,token){return new Promise(resolve=>{if(!el){resolve();return;}el.textContent='';let i=0;const tick=()=>{if(token!==typingToken){el.textContent=text;resolve();return;}i+=1;el.textContent=text.slice(0,i);if(i<text.length)setTimeout(tick,speed);else resolve();};tick();});}
  async function render(n,d){busy=true;const token=++typingToken;setRound(n,'');clear();const btns=[];for(let i=0;i<5;i++){const label=d.options[i]||'';const b=document.createElement('button');b.className='quiz-option compact';b.type='button';b.disabled=true;b.dataset.aiRound=String(n);b.dataset.aiLabel=label;const num=document.createElement('span');num.className='option-number';num.textContent=String(i+1);const h=document.createElement('strong');h.textContent='';b.append(num,h);optionsEl.appendChild(b);btns.push(b);}await typeInto(questionEl,d.question,18,token);for(let i=0;i<btns.length;i++){if(token!==typingToken)return;await typeInto(btns[i].querySelector('strong'),d.options[i],18,token);btns[i].disabled=false;await new Promise(r=>setTimeout(r,70));}if(token===typingToken)busy=false;}
  function renderFirst(c){setRound(1,'下面哪一个最接近你的问题？');clear();c.forEach((a,i)=>{const b=document.createElement('button');b.className='quiz-option quiz-option-enter';b.type='button';b.disabled=true;b.dataset.aiRound='1';b.dataset.answerId=String(a.id);b.dataset.aiLabel=title(a);const num=document.createElement('span');num.className='option-number';num.textContent=i+1;const body=document.createElement('span'),h=document.createElement('strong'),sm=document.createElement('small');body.append(h,sm);b.append(num,body);optionsEl.appendChild(b);setTimeout(()=>{b.classList.add('is-visible');let x=0;const text=title(a);const tick=()=>{h.textContent=text.slice(0,++x);if(x<text.length)setTimeout(tick,18);else{sm.textContent=summary(a);b.disabled=false;}};tick();},100+i*260);});busy=false;}
  async function startSearch(){const token=++runId,q=clean(input.value);if(q.length<2||busy)return;typingToken++;originalQuestion=q;history=[];firstSelectedId=null;busy=true;if(resultPanel)resultPanel.classList.add('hidden');quizPanel.classList.add('hidden');msg('🔍 正在匹配资料库…');const ok=await loadData();if(!ok||token!==runId){busy=false;msg('暂时无法读取资料库，请稍后重试。','error');return;}firstCandidates=answers.map(a=>({...a,_score:score(a,q)})).sort((a,b)=>b._score-a._score||Number(b.priority||0)-Number(a.priority||0)).slice(0,5);if(!firstCandidates.length){busy=false;msg('没有找到可用资料，请换个说法。','error');return;}msg('');quizPanel.classList.remove('hidden');renderFirst(firstCandidates);setTimeout(()=>quizPanel.scrollIntoView({behavior:'smooth',block:'start'}),50);}
  function goNext(){const n=round+1;if(n>5)return;render(n,contextual(n));}
  function inferTier(){const t=history.map(x=>x.label).join(' ');if(/定制|专属|系统/.test(t))return'custom';if(/完整|全流程|长期|执行方案/.test(t))return'professional';if(/详细|模板|提示词|多角度/.test(t))return'detailed';if(/步骤|操作|流程/.test(t))return'standard';return'essential';}
  function finish(){typingToken++;busy=true;const finalQ=[originalQuestion,...history.map(x=>x.label)].join(' ');const ranked=answers.map(a=>({...a,_score:score(a,finalQ)+(firstSelectedId&&Number(a.id)===Number(firstSelectedId)?15:0)})).sort((a,b)=>b._score-a._score);const a=ranked[0];if(!a){busy=false;msg('资料库暂时没有可交付内容。','error');return;}const tier=inferTier(),pid=TIER_PRODUCTS[tier],p=products.find(x=>x.id===pid)||products.find(x=>x.id===TIER_PRODUCTS.custom);if(!p){busy=false;msg('价格方案读取失败。','error');return;}const raw=Number(a._score||0),weak=raw<14,fp=weak?(products.find(x=>x.id===TIER_PRODUCTS.custom)||p):p,ft=weak?'custom':tier,composite=Math.max(35,Math.min(98,Math.round(45+raw*.7)));localStorage.setItem(MATCH_STORAGE_KEY,JSON.stringify({answer_id:Number(a.id),title:a.title||'',title_en:a.title_en||'',title_km:a.title_km||'',answer_summary:a.answer_summary||'',answer_summary_en:a.answer_summary_en||'',answer_summary_km:a.answer_summary_km||'',question:originalQuestion,selections:history.map(x=>x.label),tier:ft,product_id:fp.id,price:Number(fp.product_price),fallback:weak,score:raw,composite,analysis:['需求路径：'+originalQuestion,...history.map((x,i)=>`第${i+1}轮：${x.label}`),'匹配资料：'+title(a)].join('\n'),created_at:Date.now()}));location.href='shop.html?resume=ai-result';}
  function reset(clearInput=true){runId++;typingToken++;busy=false;round=0;history=[];firstCandidates=[];firstSelectedId=null;quizPanel.classList.add('hidden');if(resultPanel)resultPanel.classList.add('hidden');clear();msg('');if(clearInput)input.value='';}
  input.addEventListener('input',e=>{e.stopImmediatePropagation();clearTimeout(idleTimer);runId++;typingToken++;if(composing)return;const q=clean(input.value);if(q.length>=2)idleTimer=setTimeout(startSearch,3500);},true);
  input.addEventListener('compositionstart',e=>{e.stopImmediatePropagation();composing=true;clearTimeout(idleTimer);},true);
  input.addEventListener('compositionend',e=>{e.stopImmediatePropagation();composing=false;clearTimeout(idleTimer);if(clean(input.value).length>=2)idleTimer=setTimeout(startSearch,3500);},true);
  input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.stopImmediatePropagation();clearTimeout(idleTimer);startSearch();}},true);
  form.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();clearTimeout(idleTimer);startSearch();},true);
  optionsEl.addEventListener('click',e=>{const b=e.target.closest?.('button.quiz-option');if(!b||b.disabled||busy){if(b){e.preventDefault();e.stopImmediatePropagation();}return;}e.preventDefault();e.stopImmediatePropagation();const r=Number(b.dataset.aiRound||round||1),label=clean(b.dataset.aiLabel||b.querySelector('strong')?.textContent||'');if(!label)return;history=history.slice(0,r-1);history[r-1]={label};if(r===1)firstSelectedId=Number(b.dataset.answerId||0)||null;if(r>=5)finish();else goNext();},true);
  backBtn?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(busy)return;if(round<=1){reset(false);return;}typingToken++;history=history.slice(0,round-2);const n=round-1;if(n===1)renderFirst(firstCandidates);else render(n,contextual(n));},true);
  restartBtn?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();reset(true);input.focus();},true);
  loadData().catch(()=>{});
})();