(()=>{
'use strict';
const $=id=>document.getElementById(id);
function init(){
 const F=$('problemForm'),N=$('problemInput'),Q=$('quizPanel'),R=$('resultPanel'),X=$('quizOptions'),S=$('quizStepLabel'),B=$('quizProgressBar'),O=$('originalQuestion'),H=$('quizQuestion'),P=$('quizHelp'),BK=$('quizBackButton'),RS=$('restartMatchButton'),RT=$('resultTitle'),RU=$('resultSummary'),RC=$('resultConfidence'),RR=$('resultTier'),RP=$('resultPrice'),DL=$('deliveryList'),RQ=$('resultQuestion'),RL=$('resultSelections'),M=$('problemMessage');
 if(!F||!N||!Q||!X||F.dataset.gyxLiveSearch==='1')return;
 F.dataset.gyxLiveSearch='1';
 let rows=[],products=[],question='',history=[],busy=false,dbPromise=null,lastResult=null;
 const CACHE_KEY='gyx_ai_search_cache_v11',CACHE_MS=10*60*1000;
 const locale=()=>window.GYXLanguage?.current?.()||window.GYXI18N?.locale||'zh-CN';
 const pick=(r,b)=>window.GYXLanguage?.pick?.(r,b,locale())||(locale()==='en'?(r?.[b+'_en']||r?.[b]):locale()==='km'?(r?.[b+'_km']||r?.[b]):r?.[b])||'';
 const norm=s=>String(s||'').toLowerCase().replace(/[\s，。！？、；：,.!?;:()（）【】\[\]"'“”‘’_\-\/\\]+/g,'');
 const grams=s=>{s=norm(s);const a=new Set();if(!s)return a;if(s.length<2){a.add(s);return a}for(let i=0;i<s.length-1;i++)a.add(s.slice(i,i+2));return a};
 const sim=(a,b)=>{a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;const x=grams(a),y=grams(b);let hit=0;x.forEach(v=>{if(y.has(v))hit++});return x.size&&y.size?Math.min(1,(hit/x.size)*.68+(hit/y.size)*.32):0};
 const kws=r=>Array.isArray(r?.keywords)?r.keywords.filter(Boolean):[];
 const title=r=>pick(r,'title')||r?.title||'';
 const summary=r=>pick(r,'answer_summary')||r?.answer_summary||'';
 const detail=r=>pick(r,'answer_detail')||r?.answer_detail_zh||'';
 const rowText=r=>[title(r),...kws(r),summary(r),detail(r),r?.module_code,r?.source_name].filter(Boolean).join(' ');
 function lexicalScore(r,s){const q=norm(s);if(!q)return 0;let exact=0,t=sim(s,title(r)),k=0;for(const kw of kws(r)){const nk=norm(kw);if(!nk)continue;if(nk===q)exact=Math.max(exact,.98);else if(q.length>=2&&(nk.includes(q)||q.includes(nk)))exact=Math.max(exact,.82);k=Math.max(k,sim(s,kw))}const sm=sim(s,summary(r)),dt=sim(s,detail(r));return Math.max(exact,Math.min(.99,t*.48+k*.32+sm*.14+dt*.06))}
 function contextualScore(r){let total=lexicalScore(r,question)*1.25,weight=1.25;history.forEach((h,i)=>{const w=.78+i*.16;const s=Math.max(lexicalScore(r,h.label),...(h.terms||[]).map(v=>lexicalScore(r,v)));total+=s*w;weight+=w});const priority=Math.max(0,Math.min(100,Number(r.priority||0)))/100;return Math.min(.999,total/weight*.92+priority*.08)}
 async function rest(path){const c=window.GYX_CONFIG;if(!c)throw new Error('CONFIG_MISSING');const res=await fetch(c.url+'/rest/v1/'+path,{headers:{apikey:c.publishableKey,Authorization:'Bearer '+c.publishableKey,Accept:'application/json'},cache:'default'});if(!res.ok)throw new Error('DB_'+res.status);return res.json()}
 function loadCache(){try{const c=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'null');if(c&&Date.now()-c.ts<CACHE_MS&&Array.isArray(c.rows)&&c.rows.length){rows=c.rows;products=Array.isArray(c.products)?c.products:[];return true}}catch{}return false}
 function saveCache(){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({ts:Date.now(),rows,products}))}catch{}}
 async function db(){if(rows.length)return true;if(loadCache())return true;if(dbPromise)return dbPromise;dbPromise=(async()=>{try{rows=await rest('product_answer_options?select=id,answer_code,module_code,title,title_en,title_km,keywords,answer_summary,answer_summary_en,answer_summary_km,answer_detail_zh,answer_detail_en,answer_detail_km,product_id,priority,source_name&is_active=eq.true&limit=1500');products=await rest('products?select=id,product_name,product_price,description,is_active&is_active=eq.true&limit=100').catch(()=>[])||[];if(!rows.length)throw new Error('NO_ROWS');saveCache();return true}catch(e){if(M){M.textContent='暂时无法连接资料库，请稍后重试';M.className='form-message show error'}return false}finally{dbPromise=null}})();return dbPromise}
 function rank(){return rows.map(r=>({r,s:contextualScore(r)})).sort((a,b)=>b.s-a.s||Number(b.r.priority||0)-Number(a.r.priority||0))}
 function diverseTop(list,count=5){const out=[],used=new Set(history.map(h=>String(h.candidateId||'')));for(const item of list){if(used.has(String(item.r.id)))continue;const lbl=title(item.r);if(!lbl)continue;let tooClose=false;for(const x of out){if(sim(lbl,title(x.r))>.68){tooClose=true;break}const a=new Set(kws(item.r).map(norm)),b=new Set(kws(x.r).map(norm));let overlap=0;a.forEach(v=>{if(v&&b.has(v))overlap++});if(overlap>=3){tooClose=true;break}}if(tooClose)continue;out.push(item);if(out.length>=count)break}if(out.length<count){for(const item of list){if(out.includes(item)||used.has(String(item.r.id)))continue;out.push(item);if(out.length>=count)break}}return out}
 function roundQuestion(round,lead){const l=lead?`「${lead}」`:'';const qs=[`下面哪一种方向最接近你真正想解决的问题？`,`结合刚才的选择，${l}里哪一种更符合你的实际目标？`,`继续收窄需求，下面哪一种更符合你的实际使用场景？`,`已经接近目标，下面哪一种更符合你现在最需要解决的重点？`,`最后确认：你最希望系统最终为你匹配哪一种方案？`];return qs[Math.max(0,Math.min(4,round-1))]}
 function optionTerms(r){return [title(r),...kws(r).slice(0,8),summary(r)].filter(Boolean)}
 function showRound(){const round=history.length+1,ranked=rank(),opts=diverseTop(ranked,5),lead=title(ranked[0]?.r);Q.classList.remove('hidden');R?.classList.add('hidden');S.textContent=`第 ${round} / 5 轮`;B.style.width=`${round*20}%`;O.textContent=`“${question}”`;H.textContent=roundQuestion(round,lead);if(P)P.textContent='每次选择后都会重新计算整个资料库，不使用固定答案模板。';X.replaceChildren();opts.forEach((it,i)=>{const b=document.createElement('button');b.type='button';b.className='quiz-option';b.innerHTML=`<span>${i+1}</span><strong></strong>`;b.querySelector('strong').textContent=title(it.r);b.addEventListener('click',()=>choose(it));X.appendChild(b)});if(BK)BK.disabled=history.length===0}
 async function choose(item){if(busy)return;busy=true;try{history.push({label:title(item.r),terms:optionTerms(item.r),candidateId:item.r.id});if(history.length<5){showRound();return}showResult()}finally{busy=false}}
 function findProduct(r){let p=products.find(x=>String(x.id)===String(r?.product_id));if(!p)p=products.find(x=>String(x.id)==='answer-standard');if(!p)p=products[0]||null;return p}
 function tierName(p){const n=Number(p?.product_price||0);if(n>=39)return'深度私人方案';if(n>=19)return'专业执行方案';if(n>=9)return'完整方案';return'要点答案'}
 function dynamicConfidence(ranked){const a=ranked[0]?.s||0,b=ranked[1]?.s||0;const margin=Math.max(0,a-b);const choiceCoherence=history.length?history.reduce((sum,h)=>sum+Math.max(lexicalScore(ranked[0]?.r,h.label),...(h.terms||[]).map(v=>lexicalScore(ranked[0]?.r,v))),0)/history.length:0;return Math.max(61,Math.min(98,Math.round(54+a*25+choiceCoherence*14+margin*18)))}
 function showResult(){const ranked=rank(),best=ranked[0]?.r;if(!best)return;const p=findProduct(best),confidence=dynamicConfidence(ranked),alts=ranked.slice(1,6).map(x=>({id:x.r.id,title:title(x.r),summary:summary(x.r),keywords:kws(x.r),score:x.s}));lastResult={question,selections:history.map(h=>h.label),selection_terms:history.map(h=>h.terms),answer:{...best,title:title(best),answer_summary:summary(best),keywords:kws(best)},product:p,tier:tierName(p),confidence,alternatives:alts,score:ranked[0]?.s||0};window.GYX_CURRENT_AI_MATCH=lastResult;Q.classList.add('hidden');R.classList.remove('hidden');if(RT)RT.textContent=title(best)||'已匹配到私人方案';if(RU)RU.textContent=summary(best)||'系统已根据5轮真实选择从资料库中重新排序并锁定最相关方案。';if(RC)RC.textContent=confidence+'%';if(RR)RR.textContent=tierName(p);if(RP)RP.textContent=Number(p?.product_price||0).toFixed(Number(p?.product_price||0)%1?2:2);if(DL){DL.replaceChildren();history.slice(0,3).forEach(h=>{const li=document.createElement('li');li.textContent=h.label;DL.appendChild(li)})}if(RQ)RQ.textContent=question;if(RL){RL.replaceChildren();history.forEach(h=>{const li=document.createElement('li');li.textContent=h.label;RL.appendChild(li)})}window.dispatchEvent(new CustomEvent('gyx:raw-result-ready',{detail:{match:lastResult}}))}
 async function start(e){e.preventDefault();if(busy)return;const q=String(N.value||'').trim();if(q.length<2){if(M){M.textContent='请输入至少2个字';M.className='form-message show error'}return}busy=true;try{question=q;history=[];lastResult=null;window.GYX_CURRENT_AI_MATCH=null;if(M){M.textContent='';M.className='form-message'}if(!await db())return;showRound()}finally{busy=false}}
 F.addEventListener('submit',start);
 BK?.addEventListener('click',()=>{if(!history.length)return;history.pop();showRound()});
 RS?.addEventListener('click',()=>{history=[];showRound()});
 window.GYX_AI_SEARCH_ENGINE={rank:()=>rank().slice(0,20),rows:()=>rows};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();