(()=>{
'use strict';
const $=id=>document.getElementById(id);
function init(){
 const F=$('problemForm'),N=$('problemInput'),Q=$('quizPanel'),R=$('resultPanel'),X=$('quizOptions'),S=$('quizStepLabel'),B=$('quizProgressBar'),O=$('originalQuestion'),H=$('quizQuestion'),P=$('quizHelp'),BK=$('quizBackButton'),RS=$('restartMatchButton'),RT=$('resultTitle'),RU=$('resultSummary'),RC=$('resultConfidence'),RR=$('resultTier'),RP=$('resultPrice'),DL=$('deliveryList'),RQ=$('resultQuestion'),RL=$('resultSelections'),M=$('problemMessage');
 if(!F||!N||!Q||!X||F.dataset.gyxLiveSearch==='1')return;
 F.dataset.gyxLiveSearch='1';
 let rows=[],products=[],question='',history=[],busy=false,dbPromise=null,lastResult=null;
 const CACHE_KEY='gyx_ai_search_cache_v6',CACHE_MS=10*60*1000;
 const answerProduct={essential:'answer-essential',standard:'answer-standard',detailed:'answer-detailed',professional:'answer-professional',custom:'answer-custom'};
 const locale=()=>window.GYXLanguage?.current?.()||window.GYXI18N?.locale||'zh-CN';
 const pick=(r,b)=>window.GYXLanguage?.pick?.(r,b,locale())||(locale()==='en'?(r?.[b+'_en']||r?.[b]):locale()==='km'?(r?.[b+'_km']||r?.[b]):r?.[b])||'';
 const ui=()=>locale()==='en'?{round:(n)=>`Round ${n} / 5`,first:'Choose the direction closest to your question',around:x=>`Around “${x}”, choose the closest next direction`,loading:'Matching…',db:'Unable to connect to the knowledge base. Please try again later.',fallback:'The most relevant plan was selected from the knowledge base.',essential:'Essential answer',standard:'Standard action plan',detailed:'Detailed action plan',professional:'Professional execution plan',delivery:['Execution steps for this question','Ready-to-use tools, methods and templates','Result checks and optimization suggestions'],suffix:' matched plan'}:locale()==='km'?{round:n=>`ជុំទី ${n} / 5`,first:'សូមជ្រើសរើសទិសដៅដែលជិតបំផុតនឹងសំណួររបស់អ្នក',around:x=>`ជុំវិញ “${x}” សូមជ្រើសរើសទិសដៅបន្ទាប់ដែលជិតបំផុត`,loading:'កំពុងផ្គូផ្គង…',db:'មិនអាចភ្ជាប់មូលដ្ឋានចំណេះដឹងបានទេ សូមព្យាយាមម្ដងទៀត។',fallback:'បានជ្រើសរើសផែនការដែលពាក់ព័ន្ធបំផុតពីមូលដ្ឋានចំណេះដឹង។',essential:'ចម្លើយសង្ខេប',standard:'ផែនការស្តង់ដារ',detailed:'ផែនការលម្អិត',professional:'ផែនការអនុវត្តវិជ្ជាជីវៈ',delivery:['ជំហានអនុវត្តសម្រាប់សំណួរនេះ','ឧបករណ៍ វិធីសាស្ត្រ និងគំរូដែលអាចប្រើបានភ្លាម','ការត្រួតពិនិត្យលទ្ធផល និងការកែលម្អ'],suffix:' ផែនការដែលផ្គូផ្គង'}:{round:n=>`第 ${n} / 5 轮`,first:'请选择与你当前问题最接近的方向',around:x=>`围绕“${x}”，请选择下一步最接近的方向`,loading:'正在匹配…',db:'暂时无法连接资料库，请稍后重试',fallback:'已根据你的问题和五轮选择，从资料库选出最相关方案。',essential:'要点答案',standard:'标准操作答案',detailed:'详细实操方案',professional:'专业执行方案',delivery:['针对当前问题的执行步骤','可直接使用的工具、方法与模板','结果检查与优化建议'],suffix:'匹配方案'};
 const norm=s=>String(s||'').toLowerCase().replace(/[\s，。！？、；：,.!?;:()（）【】\[\]"'“”‘’_\-\/\\]+/g,'');
 const grams=s=>{s=norm(s);const a=new Set();if(s.length<2){if(s)a.add(s);return a}for(let i=0;i<s.length-1;i++)a.add(s.slice(i,i+2));return a};
 const sim=(a,b)=>{a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;const short=a.length<=6?a:b.length<=6?b:'';const long=short===a?b:a;if(short&&long.includes(short)){const ratio=short.length/Math.max(short.length,long.length);return Math.min(.94,.50+ratio*.38)}const x=grams(a),y=grams(b);let hit=0;x.forEach(v=>{if(y.has(v))hit++});return x.size&&y.size?Math.min(1,(hit/x.size)*.68+(hit/y.size)*.32):0};
 const kws=r=>Array.isArray(r.keywords)?r.keywords:[];
 const titles=r=>[r.title,r.title_en,r.title_km].filter(Boolean);
 const summaries=r=>[r.answer_summary,r.answer_summary_en,r.answer_summary_km].filter(Boolean);
 const text=r=>[...titles(r),...kws(r),...summaries(r),r.answer_detail_zh].filter(Boolean).join(' ');
 function score(r,s){const q=norm(s);if(!q)return 0;let title=0,titleText='';for(const v of titles(r)){const nv=norm(v);const ss=sim(s,v);if(ss>title){title=ss;titleText=nv}if(nv===q)return .99}let exactKw=0,bestKw=0;for(const k of kws(r)){const nk=norm(k);if(!nk)continue;if(nk===q)exactKw=Math.max(exactKw,.96);else if(q.length>=4&&nk.includes(q))exactKw=Math.max(exactKw,.84);else if(nk.length>=4&&q.includes(nk)){const coverage=nk.length/Math.max(nk.length,q.length);exactKw=Math.max(exactKw,.50+.32*coverage)}bestKw=Math.max(bestKw,sim(s,k))}let summary=0;summaries(r).forEach(v=>summary=Math.max(summary,sim(s,v)));const detail=sim(s,r.answer_detail_zh);let weighted=title*.54+bestKw*.28+summary*.12+detail*.06;if(q.length>=4&&titleText.includes(q)){const coverage=q.length/Math.max(q.length,titleText.length);weighted=Math.max(weighted,.72+.22*coverage)}return Math.max(0,Math.min(.99,Math.max(weighted,exactKw)))}
 async function rest(path){const c=window.GYX_CONFIG;if(!c)throw new Error('CONFIG_MISSING');const res=await fetch(c.url+'/rest/v1/'+path,{headers:{apikey:c.publishableKey,Authorization:'Bearer '+c.publishableKey,Accept:'application/json'},cache:'default'});if(!res.ok)throw new Error('DB_'+res.status);return res.json()}
 function loadCache(){try{const c=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'null');if(c&&Date.now()-c.ts<CACHE_MS&&Array.isArray(c.rows)&&c.rows.length){rows=c.rows;products=Array.isArray(c.products)?c.products:[];return true}}catch{}return false}
 function saveCache(){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({ts:Date.now(),rows,products}))}catch{}}
 async function db(){if(rows.length)return true;if(loadCache())return true;if(dbPromise)return dbPromise;dbPromise=(async()=>{try{rows=await rest('product_answer_options?select=id,module_code,title,title_en,title_km,keywords,answer_summary,answer_summary_en,answer_summary_km,answer_detail_zh,priority,is_active&is_active=eq.true&limit=1000');if(!Array.isArray(rows)||!rows.length)throw new Error('NO_ROWS');products=await rest('products?select=id,product_name,product_price,description&is_active=eq.true&limit=100').catch(()=>[])||[];saveCache();return true}catch(e){if(M){M.textContent=ui().db;M.className='form-message show error'}return false}finally{dbPromise=null}})();return dbPromise}
 function historyLabel(h){const r=rows.find(x=>String(x.id)===String(h.id));return r?pick(r,'title'):(h.label||'')}
 function rankedAll(){const used=new Set(history.map(v=>String(v.id))),last=history.at(-1)?.rawLabel||history.at(-1)?.label||'',path=[question,...history.map(v=>v.rawLabel||v.label)].join(' ');return rows.map(r=>{let s=!history.length?score(r,question):score(r,last)*.52+score(r,question)*.30+score(r,path)*.18;return{r,s}}).filter(v=>!used.has(String(v.r.id))).sort((a,b)=>b.s-a.s||(+b.r.priority||0)-(+a.r.priority||0))}
 function options(){const ranked=rankedAll(),out=[],seen=new Set();for(const v of ranked){const label=String(pick(v.r,'title')||v.r.title||'').trim(),key=norm(label);if(!label||seen.has(key))continue;seen.add(key);out.push({id:v.r.id,label,rawLabel:v.r.title||label,row:v.r,score:v.s});if(out.length===5)break}if(out.length<5){for(const r of rows.slice().sort((a,b)=>(+b.priority||0)-(+a.priority||0))){if(history.some(v=>String(v.id)===String(r.id)))continue;const label=String(pick(r,'title')||r.title||'').trim(),key=norm(label);if(!label||seen.has(key))continue;seen.add(key);out.push({id:r.id,label,rawLabel:r.title||label,row:r,score:score(r,question)});if(out.length===5)break}}return out.slice(0,5)}
 function paint(round){const opts=options(),U=ui();S.textContent=U.round(round);if(B)B.style.width=round*20+'%';O.textContent=`“${question}”`;const previous=history.length?historyLabel(history.at(-1)):question;H.textContent=round===1?U.first:U.around(previous);if(P)P.textContent='';if(BK)BK.classList.toggle('hidden',round===1);X.replaceChildren();opts.forEach((o,i)=>{const b=document.createElement('button');b.type='button';b.className='quiz-option compact';b.dataset.id=o.id;b.dataset.label=o.label;b.dataset.rawLabel=o.rawLabel;b.dataset.matchScore=String(o.score);b.innerHTML=`<span class="option-number">${i+1}</span><strong>${o.label}</strong>`;X.appendChild(b)});Q.classList.remove('hidden');busy=false;requestAnimationFrame(()=>Q.scrollIntoView({behavior:'auto',block:'nearest'}))}
 function confidenceFor(best){const original=score(best,question),weights=[.06,.10,.14,.25,.45];let pathScore=0,weightTotal=0;history.forEach((h,i)=>{const w=weights[i]||.1,base=h.rawLabel||h.label,optionScore=Number.isFinite(h.score)?h.score:score(best,base),answerFit=score(best,base);pathScore+=(optionScore*.35+answerFit*.65)*w;weightTotal+=w});pathScore=weightTotal?pathScore/weightTotal:original;const raw=Math.max(0,Math.min(.99,original*.38+pathScore*.62));const calibrated=Math.round(54+raw*44);return{raw,percent:Math.max(54,Math.min(98,calibrated))}}
 function final(){const selected=history.at(-1);let best=selected?rows.find(r=>String(r.id)===String(selected.id)):null;if(!best){const path=[question,...history.map(v=>v.rawLabel||v.label)].join(' ');best=rows.map(r=>({r,s:score(r,path)})).sort((a,b)=>b.s-a.s)[0]?.r||null}if(!best){busy=false;return}const metric=confidenceFor(best),raw=metric.raw,conf=metric.percent;let tier=/完整|全流程|系统|长期/.test(text(best))?'professional':/详细|模板|案例|清单/.test(text(best))?'detailed':/步骤|教程|操作|方法|流程/.test(text(best))?'standard':'essential';const pid=answerProduct[tier]||answerProduct.essential,p=products.find(x=>x.id===pid)||null,U=ui(),title=pick(best,'title')||best.title,summary=pick(best,'answer_summary')||U.fallback;Q.classList.add('hidden');R?.classList.remove('hidden');if(RT)RT.textContent=`“${title}”${U.suffix}`;if(RU)RU.textContent=summary;if(RC)RC.textContent=conf+'%';if(RR)RR.textContent={professional:U.professional,detailed:U.detailed,standard:U.standard,essential:U.essential}[tier];if(RP&&p)RP.textContent=Number(p.product_price||0).toFixed(2);if(DL){DL.replaceChildren();U.delivery.forEach(v=>{const li=document.createElement('li');li.textContent=v;DL.appendChild(li)})}if(RQ)RQ.textContent=question;if(RL){RL.replaceChildren();history.forEach(v=>{const li=document.createElement('li');li.textContent=historyLabel(v);RL.appendChild(li)})}lastResult={best,p,tier,conf,raw};window.GYX_CURRENT_AI_MATCH={answer:best,product:p,tier,question,selections:history.map(v=>historyLabel(v)),confidence:conf,local_score:raw,needs_cloud_assist:raw<.55};busy=false}
 F.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const v=String(N.value||'').trim();if(v.length<1)return;busy=true;question=v;history=[];lastResult=null;R?.classList.add('hidden');Q.classList.add('hidden');if(M){M.textContent=rows.length||loadCache()?'':ui().loading;M.className=M.textContent?'form-message show':'form-message'}try{N.blur()}catch{}if(!(await db())){busy=false;return}if(M){M.textContent='';M.className='form-message'}paint(1)});
 X.addEventListener('click',e=>{const b=e.target.closest('.quiz-option');if(!b||busy)return;busy=true;history.push({id:b.dataset.id,label:b.dataset.label,rawLabel:b.dataset.rawLabel||b.dataset.label,score:Number(b.dataset.matchScore)||0});history.length>=5?final():paint(history.length+1)});
 BK?.addEventListener('click',()=>{if(busy||!history.length)return;history.pop();paint(history.length+1)});
 RS?.addEventListener('click',()=>{history=[];question='';lastResult=null;Q.classList.add('hidden');R?.classList.add('hidden');N.value=''});
 window.addEventListener('gyx:languagechange',()=>{if(!rows.length)return;if(R&&!R.classList.contains('hidden')&&lastResult){final();return}if(Q&&!Q.classList.contains('hidden'))paint(history.length+1)});
 const preload=()=>db();if('requestIdleCallback'in window)requestIdleCallback(preload,{timeout:1200});else setTimeout(preload,300);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();