const KEYS={products:"gyx_products_v1",orders:"gyx_orders_v1",settings:"gyx_settings_v1"};
const defaults={
 settings:{name:"全球优选",telegram:"https://t.me/your_username",network:"USDT-TRC20",wallet:"请在管理后台填写真实TRC20地址",minutes:15},
 products:[
  {id:"p1",name:"AI 视频模板包",desc:"短视频镜头、文案与提示词模板合集。",price:9.9,category:"模板",emoji:"🎬",deliveryType:"download",delivery:"downloads/ai-video-template.txt",stockType:"unlimited",stock:9999,active:true},
  {id:"p2",name:"ChatGPT 提示词包",desc:"电商、短视频和办公提示词合集。",price:6.9,category:"模板",emoji:"🤖",deliveryType:"download",delivery:"downloads/chatgpt-prompts.txt",stockType:"unlimited",stock:9999,active:true},
  {id:"p3",name:"数字营销教程",desc:"流量获取、成交转化与日常运营教程。",price:12.8,category:"教程",emoji:"📚",deliveryType:"download",delivery:"downloads/digital-marketing-guide.txt",stockType:"limited",stock:20,active:true},
  {id:"p4",name:"软件激活码",desc:"付款后自动发放一条未使用激活码。",price:19.9,category:"软件",emoji:"🔑",deliveryType:"code",delivery:"GYX-DEMO-2026-8888",stockType:"limited",stock:10,active:true}
 ]
};
function getData(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}}
function saveData(key,v){localStorage.setItem(key,JSON.stringify(v))}
if(!localStorage.getItem(KEYS.settings))saveData(KEYS.settings,defaults.settings);
if(!localStorage.getItem(KEYS.products))saveData(KEYS.products,defaults.products);
if(!localStorage.getItem(KEYS.orders))saveData(KEYS.orders,[]);
let settings=getData(KEYS.settings,defaults.settings),products=getData(KEYS.products,defaults.products),orders=getData(KEYS.orders,[]);
let selected=null,currentOrder=null,timer=null,currentCategory="全部";
const $=id=>document.getElementById(id);
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function applySettings(){document.title=`${settings.name}｜数字商品自助下单`;$("brandName").textContent=settings.name;$("footerBrand").textContent=settings.name;$("supportLink").href=settings.telegram||"#"}
function categories(){return ["全部",...new Set(products.filter(p=>p.active).map(p=>p.category||"其他"))]}
function renderCategories(){ $("categoryBar").innerHTML=categories().map(c=>`<button class="category-btn ${c===currentCategory?"active":""}" onclick="setCategory('${escapeHtml(c)}')">${escapeHtml(c)}</button>`).join("")}
window.setCategory=c=>{currentCategory=c;renderCategories();renderProducts()}
function renderProducts(){products=getData(KEYS.products,defaults.products);const q=$("searchInput").value.trim().toLowerCase();const list=products.filter(p=>p.active&&(currentCategory==="全部"||p.category===currentCategory)&&(`${p.name} ${p.desc} ${p.category}`).toLowerCase().includes(q));$("productGrid").innerHTML=list.map(p=>{const sold=p.stockType==="limited"&&Number(p.stock)<=0;return `<article class="product-card ${sold?"soldout":""}"><div class="product-cover"><span class="stock-tag">${p.stockType==="unlimited"?"无限库存":"库存 "+p.stock}</span><span class="product-icon">${escapeHtml(p.emoji||"📦")}</span></div><div class="product-body"><span class="category-label">${escapeHtml(p.category||"其他")}</span><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.desc)}</p><div class="product-bottom"><span class="price">${Number(p.price).toFixed(2)} USDT</span><button class="primary" ${sold?"disabled":""} onclick="openOrder('${p.id}')">${sold?"已售罄":"立即购买"}</button></div></div></article>`}).join("");$("emptyState").classList.toggle("hidden",list.length>0)}
window.openOrder=id=>{products=getData(KEYS.products,defaults.products);selected=products.find(p=>p.id===id);if(!selected)return;$("modalEmoji").textContent=selected.emoji||"📦";$("modalName").textContent=selected.name;$("modalDesc").textContent=selected.desc;$("modalPrice").textContent=Number(selected.price).toFixed(2);$("emailInput").value="";$("telegramInput").value="";$("noteInput").value="";showStep("orderStep");openModal("productModal")}
function showStep(id){["orderStep","paymentStep","successStep"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
function openModal(id){$(id).classList.remove("hidden")}
function closeModal(id){$(id).classList.add("hidden");if(id==="productModal")clearInterval(timer)}
function createOrder(){const email=$("emailInput").value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){alert("请输入正确的收货邮箱");return}const unique=(Math.floor(Math.random()*89)+10)/1000;currentOrder={id:"GYX"+new Date().getFullYear()+Date.now().toString().slice(-9),productId:selected.id,productName:selected.name,email,telegram:$("telegramInput").value.trim(),note:$("noteInput").value.trim(),amount:(Number(selected.price)+unique).toFixed(3),network:settings.network,wallet:settings.wallet,status:"waiting",createdAt:new Date().toISOString(),delivery:""};orders=getData(KEYS.orders,[]);orders.unshift(currentOrder);saveData(KEYS.orders,orders);$("orderNo").textContent=currentOrder.id;$("networkText").textContent=currentOrder.network;$("payAmount").textContent=currentOrder.amount;$("walletInput").value=currentOrder.wallet;showStep("paymentStep");startTimer(Number(settings.minutes||15)*60)}
function startTimer(sec){clearInterval(timer);const draw=()=>{const m=String(Math.floor(sec/60)).padStart(2,"0"),s=String(sec%60).padStart(2,"0");$("countdown").textContent=`${m}:${s}`;if(sec--<=0){clearInterval(timer);updateOrderStatus(currentOrder.id,"expired");$("paymentStatus").className="status";$("paymentStatus").textContent="订单已过期，请重新创建订单。"}};draw();timer=setInterval(draw,1000)}
function updateOrderStatus(id,status,delivery=""){orders=getData(KEYS.orders,[]);const i=orders.findIndex(o=>o.id===id);if(i>=0){orders[i].status=status;orders[i].delivery=delivery;orders[i].updatedAt=new Date().toISOString();saveData(KEYS.orders,orders)}}
function simulatePaid(){if(!currentOrder)return;products=getData(KEYS.products,defaults.products);const i=products.findIndex(p=>p.id===currentOrder.productId);if(i<0)return;const p=products[i];if(p.stockType==="limited"){if(Number(p.stock)<=0){alert("库存不足");return}p.stock=Number(p.stock)-1;saveData(KEYS.products,products)}let delivery="";if(p.deliveryType==="download")delivery=`<a href="${escapeHtml(p.delivery)}" download>立即下载商品</a>`;else if(p.deliveryType==="code")delivery=`<strong>卡密：</strong><br>${escapeHtml(p.delivery)}`;else if(p.deliveryType==="account")delivery=`<strong>账号信息：</strong><br>${escapeHtml(p.delivery)}`;else delivery=`<a href="${escapeHtml(p.delivery)}" target="_blank">打开交付链接</a>`;updateOrderStatus(currentOrder.id,"paid",p.delivery);clearInterval(timer);$("paymentStatus").className="status waiting";$("paymentStatus").textContent="付款已确认，正在自动交付……";setTimeout(()=>{$("deliveryEmail").textContent=currentOrder.email;$("deliveryBox").innerHTML=delivery;showStep("successStep");renderProducts()},600)}
function queryOrder(){const no=$("queryOrderNo").value.trim(),email=$("queryEmail").value.trim().toLowerCase();orders=getData(KEYS.orders,[]);const o=orders.find(x=>x.id===no&&x.email.toLowerCase()===email);if(!o){$("queryResult").innerHTML="<strong>未查询到订单</strong><p>请检查订单号和邮箱。</p>";return}const map={waiting:"等待付款",paid:"已付款并交付",expired:"已过期"};$("queryResult").innerHTML=`<strong>${escapeHtml(o.productName)}</strong><p>订单号：${escapeHtml(o.id)}<br>金额：${escapeHtml(o.amount)} USDT<br>状态：${map[o.status]||o.status}</p>`}
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
$("productModal").onclick=e=>{if(e.target===$("productModal"))closeModal("productModal")};
$("queryModal").onclick=e=>{if(e.target===$("queryModal"))closeModal("queryModal")};
$("searchInput").oninput=renderProducts;$("createOrderBtn").onclick=createOrder;$("simulatePaidBtn").onclick=simulatePaid;$("orderQueryBtn").onclick=()=>openModal("queryModal");$("queryBtn").onclick=queryOrder;
$("copyWalletBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("walletInput").value);$("copyWalletBtn").textContent="已复制";setTimeout(()=>$("copyWalletBtn").textContent="复制",1000)}catch{alert("请长按钱包地址复制")}};
applySettings();renderCategories();renderProducts();