(() => {
  'use strict';
  const db = window.gyxSupabase;
  const i18n = window.GYXI18N;
  if (!db || !i18n) return;
  const $ = (id) => document.getElementById(id);
  const t = (key) => i18n.t(key);
  const requestedMode = new URLSearchParams(location.search).get('mode');
  let mode = requestedMode === 'register' || requestedMode === 'recover' ? requestedMode : 'login';
  let activeUser = null;
  const countries=[['CN','中国','+86'],['KH','柬埔寨','+855'],['US','美国/加拿大','+1'],['GB','英国','+44'],['AU','澳大利亚','+61'],['SG','新加坡','+65'],['MY','马来西亚','+60'],['TH','泰国','+66'],['VN','越南','+84'],['PH','菲律宾','+63'],['ID','印度尼西亚','+62'],['JP','日本','+81'],['KR','韩国','+82'],['IN','印度','+91'],['AE','阿联酋','+971'],['FR','法国','+33'],['DE','德国','+49'],['IT','意大利','+39'],['ES','西班牙','+34'],['BR','巴西','+55'],['MX','墨西哥','+52'],['ZA','南非','+27'],['NG','尼日利亚','+234'],['OTHER','其他国家/地区','']];
  function L(zh,en,km){return i18n.locale==='en'?en:i18n.locale==='km'?km:zh}
  function ensureRegisterContactFields(){
    if($('registerContactGroup'))return;
    const emailGroup=$('authEmail')?.closest('.form-group');if(!emailGroup)return;
    const wrap=document.createElement('div');wrap.id='registerContactGroup';wrap.className='hidden';
    const options=countries.map(([code,name,dial])=>`<option value="${code}" data-dial="${dial}">${name}${dial?' '+dial:''}</option>`).join('');
    wrap.innerHTML=`<div class="form-group"><label id="registerCountryLabel" for="registerCountry"></label><select id="registerCountry" class="select" required>${options}</select></div><div class="form-group"><label id="registerPhoneLabel" for="registerPhone"></label><input id="registerPhone" class="field" type="tel" maxlength="24" autocomplete="tel" inputmode="tel" required><span id="registerPhoneHint" class="form-help"></span></div>`;
    emailGroup.insertAdjacentElement('afterend',wrap);$('registerCountry')?.addEventListener('change',updatePhoneHint);updateRegisterLabels();
  }
  function updateRegisterLabels(){const c=$('registerCountryLabel'),p=$('registerPhoneLabel'),n=document.querySelector('label[for="displayName"]'),ni=$('displayName');if(c)c.textContent=L('地区','Region','តំបន់');if(p)p.textContent=L('注册手机号','Registration phone','លេខទូរស័ព្ទចុះឈ្មោះ');if(n)n.textContent=L('注册账号名','Registration account name','ឈ្មោះគណនីចុះឈ្មោះ');if(ni)ni.placeholder=L('请输入注册账号名','Enter your registration account name','បញ្ចូលឈ្មោះគណនីចុះឈ្មោះ');updatePhoneHint()}
  function updatePhoneHint(){const s=$('registerCountry'),h=$('registerPhoneHint'),input=$('registerPhone');if(!s||!h||!input)return;const dial=s.selectedOptions[0]?.dataset?.dial||'';h.textContent=dial?L(`国际区号 ${dial}，填写本地手机号`,`Country code ${dial}; enter your local number`,`លេខកូដប្រទេស ${dial} បញ្ចូលលេខក្នុងស្រុក`):L('请输入完整国际号码，例如 +85512345678','Enter the full international number, e.g. +85512345678','បញ្ចូលលេខអន្តរជាតិពេញលេញ ឧ. +85512345678');input.placeholder=dial?L('填写本地手机号','Local phone number','លេខទូរស័ព្ទក្នុងស្រុក'):L('+国际区号 手机号','+country code phone number','+លេខកូដប្រទេស លេខទូរស័ព្ទ')}
  function normalizePhone(){const raw=String($('registerPhone')?.value||'').trim(),dial=$('registerCountry')?.selectedOptions?.[0]?.dataset?.dial||'';if(!raw)return'';if(!dial){const x=raw.replace(/[\s()\-]/g,'');return /^\+[1-9]\d{6,14}$/.test(x)?x:''}const local=raw.replace(/\D/g,'').replace(/^0+/,'');const x=dial+local;return /^\+[1-9]\d{6,14}$/.test(x)?x:''}
  function selectedCountry(){const o=$('registerCountry')?.selectedOptions?.[0];return{code:String(o?.value||''),name:String(o?.textContent||'').replace(/\s\+\d.*$/,'').trim()}}
  function showMessage(message,kind='error'){const e=$('authMessage');e.textContent=message;e.className=`form-message show ${kind}`}
  function clearMessage(){$('authMessage').className='form-message';$('authMessage').textContent=''}
  function bindPasswordToggles(){document.querySelectorAll('[data-toggle-password]').forEach(b=>{if(b.dataset.passwordBound==='1')return;b.dataset.passwordBound='1';b.addEventListener('click',()=>{const input=$(b.dataset.togglePassword);if(!input)return;const show=input.type==='password';input.type=show?'text':'password';b.textContent=t(show?'hidePassword':'showPassword');b.setAttribute('aria-pressed',String(show))})})}
  function syncPasswordToggleLabels(){document.querySelectorAll('[data-toggle-password]').forEach(b=>{const input=$(b.dataset.togglePassword);if(!input)return;b.textContent=t(input.type==='text'?'hidePassword':'showPassword')})}
  function setMode(nextMode){mode=nextMode;clearMessage();ensureRegisterContactFields();const registering=mode==='register',recovering=mode==='recover';$('displayNameGroup').classList.toggle('hidden',!registering);$('confirmPasswordGroup').classList.toggle('hidden',!registering);$('registerContactGroup')?.classList.toggle('hidden',!registering);$('displayName').required=registering;$('confirmPassword').required=registering;if($('registerPhone'))$('registerPhone').required=registering;if($('registerCountry'))$('registerCountry').required=registering;$('passwordGroup').classList.toggle('hidden',recovering);$('authPassword').disabled=recovering;$('authPassword').autocomplete=registering?'new-password':'current-password';$('forgotPasswordButton').classList.toggle('hidden',mode!=='login');$('backToLoginButton').classList.toggle('hidden',!recovering);$('loginTab').classList.toggle('active',!registering&&!recovering);$('registerTab').classList.toggle('active',registering);$('loginTab').setAttribute('aria-selected',String(!registering&&!recovering));$('registerTab').setAttribute('aria-selected',String(registering));$('authSubmit').textContent=t(recovering?'sendResetLink':registering?'signUp':'signIn');updateRegisterLabels();syncPasswordToggleLabels()}
  function isValidPassword(password){return password.length>=8&&password.length<=20}
  function authErrorText(error){const status=Number(error?.status||error?.statusCode||error?.context?.status||0),code=String(error?.code||error?.error_code||error?.name||'').toUpperCase(),raw=String(error?.message||error?.msg||error||''),m=raw.toLowerCase();if(status===429||code.includes('RATE_LIMIT')||m.includes('rate limit')||m.includes('too many requests'))return L('尝试次数过多，请稍后再试。','Too many attempts. Please try again later.','ព្យាយាមច្រើនពេក សូមសាកម្តងទៀតពេលក្រោយ។');if(m.includes('already registered'))return L('该邮箱已注册，请直接登录。','This email is already registered.','អ៊ីមែលនេះបានចុះឈ្មោះរួចហើយ។');if(m.includes('invalid login'))return L('邮箱或密码错误。','Incorrect email or password.','អ៊ីមែល ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។');return raw||t('errorGeneric')}
  function getNext(){return window.gyxSafeNext(new URLSearchParams(location.search).get('next'),'member.html')}
  async function applyPendingProfile(user){let pending=null;try{pending=JSON.parse(localStorage.getItem('gyx_pending_profile')||'null')}catch{}if(!pending||pending.email!==user.email)return;await db.from('profiles').update({display_name:pending.display_name,phone:pending.phone,phone_country_code:pending.phone_country_code||null,phone_country_name:pending.phone_country_name||null,locale:pending.locale}).eq('user_id',user.id);localStorage.removeItem('gyx_pending_profile')}
  async function recordAuthEvent(eventType){try{await window.gyxInvokeFunction('record-auth-event',{event_type:eventType})}catch{}}
  async function submitAuth(event){event.preventDefault();clearMessage();const email=String($('authEmail').value||'').trim().toLowerCase(),password=String($('authPassword').value||''),displayName=$('displayName').value.trim(),confirm=$('confirmPassword').value,phone=mode==='register'?normalizePhone():'',country=selectedCountry();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){showMessage(t('errorEmail'));return}if(mode!=='recover'&&!isValidPassword(password)){showMessage(L('密码需为 8～20 位','Password must be 8–20 characters','ពាក្យសម្ងាត់ត្រូវមាន 8–20 តួ'));return}if(mode==='register'&&password!==confirm){showMessage(t('errorPasswordMatch'));return}if(mode==='register'&&!displayName){showMessage(L('请填写注册账号名','Enter a registration account name','សូមបញ្ចូលឈ្មោះគណនីចុះឈ្មោះ'));return}if(mode==='register'&&!phone){showMessage(L('请选择地区并填写有效的注册手机号','Select a region and enter a valid registration phone number','សូមជ្រើសតំបន់ និងបញ្ចូលលេខទូរស័ព្ទត្រឹមត្រូវ'));return}const button=$('authSubmit');button.disabled=true;try{if(mode==='recover'){const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:'https://globalyouxuan-order.pages.dev/reset-password.html'});if(error)throw error;showMessage(t('resetEmailSent'),'success')}else if(mode==='register'){const profile={email,display_name:displayName,phone,phone_country_code:country.code,phone_country_name:country.name,locale:i18n.locale};localStorage.setItem('gyx_pending_profile',JSON.stringify(profile));await window.gyxInvokeFunction('register-member',{...profile,password,website:$('registerWebsite')?.value||''});const{data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;await applyPendingProfile(data.user);await recordAuthEvent('register');showMessage(t('registerSuccess'),'success');setTimeout(()=>location.href=getNext(),450)}else{const{data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;await applyPendingProfile(data.user);await recordAuthEvent('login');showMessage(L('登录成功，正在进入会员中心…','Login successful. Opening your account…','ចូលបានជោគជ័យ កំពុងបើកគណនី…'),'success');setTimeout(()=>location.href=getNext(),450)}}catch(error){showMessage(authErrorText(error))}finally{button.disabled=false;button.textContent=t(mode==='recover'?'sendResetLink':mode==='register'?'signUp':'signIn')}}
  async function inspectSession(){if(mode==='recover')return;activeUser=await window.gyxGetVerifiedUser();if(!activeUser)return;$('activeSession').classList.add('show');$('sessionEmail').textContent=activeUser.email||'';$('continueButton').href=getNext();$('authForm').classList.add('hidden')}
  async function switchAccount(){await recordAuthEvent('logout');await db.auth.signOut({scope:'local'});activeUser=null;$('activeSession').classList.remove('show');$('authForm').classList.remove('hidden');$('authEmail').focus()}
  window.addEventListener('gyx:languagechange',()=>setMode(mode));document.addEventListener('DOMContentLoaded',async()=>{ensureRegisterContactFields();bindPasswordToggles();document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('authForm').addEventListener('submit',submitAuth);$('forgotPasswordButton').addEventListener('click',()=>setMode('recover'));$('backToLoginButton').addEventListener('click',()=>setMode('login'));$('switchAccountButton').addEventListener('click',switchAccount);setMode(mode);await inspectSession()});
})();