(()=>{
'use strict';
const KEY='gyx_locale',VALID=new Set(['zh-CN','en','km']),CACHE_PREFIX='gyx_tr_v2:';
const nodeSource=new WeakMap(),attrSource=new WeakMap();
let current='zh-CN',applying=false,queued=false,seq=0;
const skipSelector='[translate="no"],[data-no-i18n],script,style,code,pre,.brand,[data-language-select],[data-set-lang],[data-lang],#problemInput,#originalQuestion,.profile-email,#profileUserId,#profileJoinedAt';
function get(){try{const v=localStorage.getItem(KEY);return VALID.has(v)?v:'zh-CN'}catch{return'zh-CN'}}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function cacheKey(locale,text){return CACHE_PREFIX+locale+':'+hash(text)}
function readCache(locale,text){try{return localStorage.getItem(cacheKey(locale,text))||''}catch{return''}}
function writeCache(locale,text,value){try{localStorage.setItem(cacheKey(locale,text),value)}catch{}}
function meaningful(s){const x=String(s||'').trim();if(!x)return false;if(/^[-–—_•·|/\\+*=<>~`'".,:;!?()（）【】\[\]{}￥$€£¥%#@^&\s0-9]+$/.test(x))return false;if(/^https?:\/\//i.test(x)||/^[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}$/.test(x))return false;if(/^[T][A-Za-z0-9]{25,}$/.test(x)||/^[0-9A-Fa-f]{64}$/.test(x))return false;return true}
function skipped(el){return !!el?.closest?.(skipSelector)}
function collect(root=document.body){const textJobs=[],attrJobs=[];if(!root)return{textJobs,attrJobs};const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||skipped(p))return NodeFilter.FILTER_REJECT;const raw=String(n.nodeValue||'');return meaningful(raw)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});let n;while((n=walker.nextNode())){if(!nodeSource.has(n))nodeSource.set(n,String(n.nodeValue||''));textJobs.push({node:n,source:nodeSource.get(n)})}const els=root.querySelectorAll?root.querySelectorAll('[placeholder],[title],[aria-label]'):[];els.forEach(el=>{if(skipped(el))return;for(const attr of ['placeholder','title','aria-label']){const v=el.getAttribute(attr);if(!meaningful(v))continue;let map=attrSource.get(el);if(!map){map={};attrSource.set(el,map)}if(!(attr in map))map[attr]=v;attrJobs.push({el,attr,source:map[attr]})}});return{textJobs,attrJobs}}
function restore(root=document.body){const {textJobs,attrJobs}=collect(root);applying=true;try{textJobs.forEach(j=>{if(j.node.isConnected)j.node.nodeValue=j.source});attrJobs.forEach(j=>{if(j.el.isConnected)j.el.setAttribute(j.attr,j.source)})}finally{applying=false}}
function syncControls(locale){document.documentElement.lang=locale;document.querySelectorAll('[data-language-select]').forEach(s=>{s.value=locale});document.querySelectorAll('[data-set-lang],[data-lang]').forEach(b=>{const v=b.dataset.setLang||b.dataset.lang;b.classList.toggle('active',v===locale)});const compact=document.querySelector('[data-lang-toggle]');if(compact)compact.textContent=locale==='en'?'EN':locale==='km'?'ខ្មែរ':'中'}
async function translateBatch(texts,locale){const unique=[...new Set(texts.map(x=>String(x||'').trim()).filter(meaningful))];const out=new Map();const missing=[];for(const t of unique){const c=readCache(locale,t);if(c)out.set(t,c);else missing.push(t)}if(!missing.length)return out;const cfg=window.GYX_CONFIG;if(!cfg?.url||!cfg?.publishableKey)return out;for(let i=0;i<missing.length;i+=60){const chunk=missing.slice(i,i+60);try{const r=await fetch(cfg.url+'/functions/v1/translate-ui',{method:'POST',headers:{'content-type':'application/json',apikey:cfg.publishableKey},body:JSON.stringify({locale,texts:chunk})});if(!r.ok)continue;const j=await r.json();for(const item of j.translations||[]){const src=String(item.source_text||'').trim(),tr=String(item.translated_text||'');if(src&&tr){out.set(src,tr);writeCache(locale,src,tr)}}}catch{}}return out}
async function apply(root=document.body,locale=current){if(!root)return;if(locale==='zh-CN'){restore(root);syncControls(locale);return}const my=++seq,{textJobs,attrJobs}=collect(root),sources=[...textJobs.map(j=>String(j.source||'').trim()),...attrJobs.map(j=>String(j.source||'').trim())].filter(meaningful),map=await translateBatch(sources,locale);if(my!==seq||locale!==current)return;applying=true;try{textJobs.forEach(j=>{const k=String(j.source||'').trim(),v=map.get(k);if(v&&j.node.isConnected)j.node.nodeValue=String(j.source).replace(k,v)});attrJobs.forEach(j=>{const k=String(j.source||'').trim(),v=map.get(k);if(v&&j.el.isConnected)j.el.setAttribute(j.attr,String(j.source).replace(k,v))})}finally{applying=false}syncControls(locale)}
async function syncProfile(locale){try{const db=window.gyxSupabase,u=await window.gyxGetVerifiedUser?.();if(!db||!u)return;await db.from('profiles').update({locale,updated_at:new Date().toISOString()}).eq('user_id',u.id);try{await db.auth.updateUser({data:{locale}})}catch{}}catch{}}
function set(locale,{sync=true}={}){if(!VALID.has(locale))return;current=locale;try{localStorage.setItem(KEY,locale)}catch{}syncControls(locale);apply(document.body,locale);window.dispatchEvent(new CustomEvent('gyx:localechange',{detail:{locale}}));if(sync)syncProfile(locale)}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply(document.body,current)})}
function bind(){document.addEventListener('change',e=>{const s=e.target.closest?.('[data-language-select]');if(s&&VALID.has(s.value))set(s.value)});document.addEventListener('click',e=>{const b=e.target.closest?.('[data-set-lang],[data-lang]');const l=b?.dataset?.setLang||b?.dataset?.lang;if(VALID.has(l)){e.preventDefault();set(l)}});window.addEventListener('storage',e=>{if(e.key===KEY&&VALID.has(e.newValue)){current=e.newValue;syncControls(current);apply(document.body,current)}});const mo=new MutationObserver(ms=>{if(applying)return;let changed=false;for(const m of ms){if(m.type==='characterData'){const n=m.target,p=n.parentElement;if(p&&!skipped(p)){nodeSource.set(n,String(n.nodeValue||''));changed=true}}else if(m.type==='childList'){for(const n of m.addedNodes){if(n.nodeType===Node.TEXT_NODE){const p=n.parentElement;if(p&&!skipped(p))nodeSource.set(n,String(n.nodeValue||''))}changed=true}}else if(m.type==='attributes'){const el=m.target;if(!skipped(el)){let map=attrSource.get(el);if(!map){map={};attrSource.set(el,map)}map[m.attributeName]=el.getAttribute(m.attributeName)||'';changed=true}}}if(changed)schedule()});mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']})}
function init(){current=get();syncControls(current);bind();apply(document.body,current);window.addEventListener('online',schedule);window.addEventListener('gyx:raw-result-ready',schedule);window.addEventListener('gyx:result-ready',schedule)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.GYXLocale={get:()=>current,set,apply:()=>apply(document.body,current),translateTexts:async texts=>translateBatch(texts,current)};
})();