(()=>{
'use strict';
const KEY='gyx_locale',VALID=new Set(['zh-CN','en','km']),CACHE_PREFIX='gyx_tr_v4:';
const nodeSource=new WeakMap(),nodeRendered=new WeakMap(),attrSource=new WeakMap(),attrRendered=new WeakMap();
const failedUntil=new Map(),inflight=new Map();
let current='zh-CN',queuedTimer=0,seq=0;
const nativeFetch=window.fetch.bind(window);
const skipSelector='[translate="no"],[data-no-i18n],script,style,code,pre,.brand,[data-language-select],[data-set-lang],[data-lang],#problemInput,#originalQuestion,.profile-email,#profileUserId,#profileJoinedAt';
function get(){try{const v=localStorage.getItem(KEY);return VALID.has(v)?v:'zh-CN'}catch{return'zh-CN'}}
function langCode(l){return l==='zh-CN'?'zh':l}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function cacheKey(locale,text){return CACHE_PREFIX+locale+':'+hash(text)}
function readCache(locale,text){try{return localStorage.getItem(cacheKey(locale,text))||''}catch{return''}}
function writeCache(locale,text,value){try{localStorage.setItem(cacheKey(locale,text),value)}catch{}}
function meaningful(s){const x=String(s||'').trim();if(!x)return false;if(/^[-–—_•·|/\\+*=<>~`'".,:;!?()（）【】\[\]{}￥$€£¥%#@^&\s0-9]+$/.test(x))return false;if(/^https?:\/\//i.test(x)||/^[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}$/.test(x))return false;if(/^[T][A-Za-z0-9]{25,}$/.test(x)||/^[0-9A-Fa-f]{64}$/.test(x))return false;return true}
function skipped(el){return !!el?.closest?.(skipSelector)}
function getAttrMap(store,el){let m=store.get(el);if(!m){m={};store.set(el,m)}return m}
function collect(root=document.body){const textJobs=[],attrJobs=[];if(!root)return{textJobs,attrJobs};const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||skipped(p))return NodeFilter.FILTER_REJECT;const raw=String(n.nodeValue||'');return meaningful(raw)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});let n;while((n=walker.nextNode())){if(!nodeSource.has(n))nodeSource.set(n,String(n.nodeValue||''));textJobs.push({node:n,source:nodeSource.get(n)})}const els=root.querySelectorAll?root.querySelectorAll('[placeholder],[title],[aria-label]'):[];els.forEach(el=>{if(skipped(el))return;for(const attr of ['placeholder','title','aria-label']){const v=el.getAttribute(attr);if(!meaningful(v))continue;const map=getAttrMap(attrSource,el);if(!(attr in map))map[attr]=v;attrJobs.push({el,attr,source:map[attr]})}});return{textJobs,attrJobs}}
function setText(node,value){nodeRendered.set(node,value);node.nodeValue=value}
function setAttr(el,attr,value){const m=getAttrMap(attrRendered,el);m[attr]=value;el.setAttribute(attr,value)}
function restore(root=document.body){const {textJobs,attrJobs}=collect(root);textJobs.forEach(j=>{if(j.node.isConnected)setText(j.node,j.source)});attrJobs.forEach(j=>{if(j.el.isConnected)setAttr(j.el,j.attr,j.source)})}
function syncControls(locale){document.documentElement.lang=locale;document.querySelectorAll('[data-language-select]').forEach(s=>{s.value=locale});document.querySelectorAll('[data-set-lang],[data-lang]').forEach(b=>{const v=b.dataset.setLang||b.dataset.lang;b.classList.toggle('active',v===locale)});const compact=document.querySelector('[data-lang-toggle]');if(compact)compact.textContent=locale==='en'?'EN':locale==='km'?'ខ្មែរ':'中'}
async function requestChunk(chunk,locale){const sig=locale+'|'+chunk.join('\u241f');if(inflight.has(sig))return inflight.get(sig);const p=(async()=>{const cfg=window.GYX_CONFIG;if(!cfg?.url||!cfg?.publishableKey)return[];const r=await nativeFetch(cfg.url+'/functions/v1/translate-ui',{method:'POST',headers:{'content-type':'application/json',apikey:cfg.publishableKey},body:JSON.stringify({locale,texts:chunk})});if(!r.ok)throw new Error('TRANSLATE_'+r.status);const j=await r.json();return Array.isArray(j.translations)?j.translations:[]})().finally(()=>inflight.delete(sig));inflight.set(sig,p);return p}
async function translateBatch(texts,locale=current){const unique=[...new Set(texts.map(x=>String(x||'').trim()).filter(meaningful))];const out=new Map(),missing=[];const now=Date.now();for(const t of unique){const c=readCache(locale,t);if(c)out.set(t,c);else if((failedUntil.get(locale+'|'+t)||0)<=now)missing.push(t)}if(!missing.length)return out;for(let i=0;i<missing.length;i+=18){const chunk=missing.slice(i,i+18);try{const rows=await requestChunk(chunk,locale);for(const item of rows){const src=String(item.source_text||'').trim(),tr=String(item.translated_text||'');if(src&&tr){out.set(src,tr);writeCache(locale,src,tr);failedUntil.delete(locale+'|'+src)}}}catch{const until=Date.now()+15000;chunk.forEach(t=>failedUntil.set(locale+'|'+t,until))}}return out}
async function localizeSearchResponse(resp,locale){if(locale==='zh-CN'||!resp?.ok)return resp;try{const data=await resp.clone().json(),targets=[];const add=v=>{if(typeof v==='string'&&meaningful(v))targets.push(v)};add(data.stage);add(data.dimension);add(data.intent);add(data.question);if(Array.isArray(data.options))data.options.forEach(add);add(data.final_plan?.text);const map=await translateBatch(targets,locale);const cv=v=>typeof v==='string'?(map.get(v.trim())||v):v;data.stage=cv(data.stage);data.dimension=cv(data.dimension);data.intent=cv(data.intent);data.question=cv(data.question);if(Array.isArray(data.options))data.options=data.options.map(cv);if(data.final_plan?.text)data.final_plan.text=cv(data.final_plan.text);return new Response(JSON.stringify(data),{status:resp.status,statusText:resp.statusText,headers:resp.headers})}catch{return resp}}
function patchFetch(){if(window.__GYX_LOCALE_FETCH_PATCHED)return;window.__GYX_LOCALE_FETCH_PATCHED=true;window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||'');let nextInit=init;if(url.includes('/functions/v1/knowledge-decision-ai')&&init?.body&&current!=='zh-CN'){try{const b=JSON.parse(String(init.body));if(b&&['final','select'].includes(b.action)){b.language=langCode(current);nextInit={...init,body:JSON.stringify(b)}}}catch{}}const resp=await nativeFetch(input,nextInit);if(url.includes('/functions/v1/wealth-search-lab'))return localizeSearchResponse(resp,current);return resp}}
async function apply(root=document.body,locale=current){if(!root)return;const my=++seq;if(locale==='zh-CN'){restore(root);syncControls(locale);return}const {textJobs,attrJobs}=collect(root),sources=[...textJobs.map(j=>String(j.source||'').trim()),...attrJobs.map(j=>String(j.source||'').trim())].filter(meaningful),map=await translateBatch(sources,locale);if(my!==seq||locale!==current)return;textJobs.forEach(j=>{const k=String(j.source||'').trim(),v=map.get(k);if(v&&j.node.isConnected)setText(j.node,String(j.source).replace(k,v))});attrJobs.forEach(j=>{const k=String(j.source||'').trim(),v=map.get(k);if(v&&j.el.isConnected)setAttr(j.el,j.attr,String(j.source).replace(k,v))});syncControls(locale)}
async function syncProfile(locale){try{const db=window.gyxSupabase,u=await window.gyxGetVerifiedUser?.();if(!db||!u)return;await db.from('profiles').update({locale,updated_at:new Date().toISOString()}).eq('user_id',u.id);try{await db.auth.updateUser({data:{locale}})}catch{}}catch{}}
function set(locale,{sync=true}={}){if(!VALID.has(locale))return;current=locale;try{localStorage.setItem(KEY,locale)}catch{}syncControls(locale);apply(document.body,locale);window.dispatchEvent(new CustomEvent('gyx:localechange',{detail:{locale}}));if(sync)syncProfile(locale)}
function schedule(delay=140){clearTimeout(queuedTimer);queuedTimer=setTimeout(()=>apply(document.body,current),delay)}
function bind(){document.addEventListener('change',e=>{const s=e.target.closest?.('[data-language-select]');if(s&&VALID.has(s.value))set(s.value)});document.addEventListener('click',e=>{const b=e.target.closest?.('[data-set-lang],[data-lang]');const l=b?.dataset?.setLang||b?.dataset?.lang;if(VALID.has(l)){e.preventDefault();set(l)}});window.addEventListener('storage',e=>{if(e.key===KEY&&VALID.has(e.newValue)){current=e.newValue;syncControls(current);apply(document.body,current)}});const mo=new MutationObserver(ms=>{let changed=false;for(const m of ms){if(m.type==='characterData'){const n=m.target,p=n.parentElement;if(!p||skipped(p))continue;const value=String(n.nodeValue||'');if(nodeRendered.get(n)===value)continue;nodeSource.set(n,value);changed=true}else if(m.type==='childList'){for(const n of m.addedNodes){if(n.nodeType===Node.TEXT_NODE){const p=n.parentElement;if(p&&!skipped(p))nodeSource.set(n,String(n.nodeValue||''))}}changed=true}else if(m.type==='attributes'){const el=m.target;if(skipped(el))continue;const attr=m.attributeName,value=el.getAttribute(attr)||'',rendered=getAttrMap(attrRendered,el)[attr];if(rendered===value)continue;getAttrMap(attrSource,el)[attr]=value;changed=true}}if(changed)schedule()});mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']})}
function init(){current=get();patchFetch();syncControls(current);bind();apply(document.body,current);window.addEventListener('online',()=>schedule(60));window.addEventListener('gyx:raw-result-ready',()=>schedule(40));window.addEventListener('gyx:result-ready',()=>schedule(40))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.GYXLocale={get:()=>current,set,apply:()=>apply(document.body,current),translateTexts:async texts=>translateBatch(texts,current)};
})();