(()=>{
'use strict';
const KEY='gyx_locale',VALID=new Set(['zh-CN','en','km']),P='gyx_tr_v7:';
const srcText=new WeakMap(),srcAttr=new WeakMap(),rendered=new WeakMap(),bundle=new Map(),inflight=new Map();
let current='zh-CN',timer=0,seq=0;
const nativeFetch=window.fetch.bind(window);
const SKIP='[translate="no"],[data-no-i18n],script,style,code,pre,.brand,[data-language-select],[data-set-lang],[data-lang],#problemInput,#originalQuestion,.profile-email,#profileUserId,#profileJoinedAt';
function get(){try{const v=localStorage.getItem(KEY);return VALID.has(v)?v:'zh-CN'}catch{return'zh-CN'}}
function h(s){let x=2166136261;for(let i=0;i<s.length;i++){x^=s.charCodeAt(i);x=Math.imul(x,16777619)}return(x>>>0).toString(36)}
function ck(l,s){return P+l+':'+h(s)}
function read(l,s){try{return localStorage.getItem(ck(l,s))||''}catch{return''}}
function write(l,s,v){try{localStorage.setItem(ck(l,s),v)}catch{}}
function meaningful(s){const x=String(s||'').trim();return !!x&&!/^[-–—_•·|/\\+*=<>~`'".,:;!?()（）【】\[\]{}￥$€£¥%#@^&\s0-9]+$/.test(x)&&!/^https?:\/\//i.test(x)&&!/^[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}$/.test(x)&&!/^[T][A-Za-z0-9]{25,}$/.test(x)&&!/^[0-9A-Fa-f]{64}$/.test(x)}
function skipped(el){return !!el?.closest?.(SKIP)}
function amap(el){let m=srcAttr.get(el);if(!m){m={};srcAttr.set(el,m)}return m}
function collect(root=document.body){const texts=[],attrs=[];if(!root)return{texts,attrs};const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||skipped(p)||!meaningful(n.nodeValue))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});let n;while((n=w.nextNode())){if(!srcText.has(n))srcText.set(n,String(n.nodeValue||''));texts.push({n,s:srcText.get(n)})}root.querySelectorAll?.('[placeholder],[title],[aria-label]').forEach(el=>{if(skipped(el))return;for(const a of ['placeholder','title','aria-label']){const v=el.getAttribute(a);if(!meaningful(v))continue;const m=amap(el);if(!(a in m))m[a]=v;attrs.push({el,a,s:m[a]})}});return{texts,attrs}}
function controls(l){document.documentElement.lang=l;document.querySelectorAll('[data-language-select]').forEach(x=>x.value=l);document.querySelectorAll('[data-set-lang],[data-lang]').forEach(b=>{const v=b.dataset.setLang||b.dataset.lang;b.classList.toggle('active',v===l)});const c=document.querySelector('[data-lang-toggle]');if(c)c.textContent=l==='en'?'EN':l==='km'?'ខ្មែរ':'中'}
function restore(root=document.body){const j=collect(root);j.texts.forEach(x=>{if(x.n.isConnected){rendered.set(x.n,x.s);x.n.nodeValue=x.s}});j.attrs.forEach(x=>{if(x.el.isConnected)x.el.setAttribute(x.a,x.s)})}
async function loadBundle(l,{force=false}={}){if(l==='zh-CN')return false;if(!force&&bundle.get(l)==='done')return false;const old=bundle.get(l);if(!force&&old?.then)return old;const p=(async()=>{const c=window.GYX_CONFIG;if(!c?.url||!c?.publishableKey)throw 0;const r=await nativeFetch(c.url+'/functions/v1/translate-ui',{method:'POST',headers:{'content-type':'application/json',apikey:c.publishableKey},body:JSON.stringify({action:'bundle',locale:l})});if(!r.ok)throw 0;const j=await r.json();for(const x of j.translations||[]){const s=String(x.source_text||'').trim(),t=String(x.translated_text||'');if(s&&t)write(l,s,t)}bundle.set(l,'done');return true})().catch(()=>{bundle.delete(l);return false});bundle.set(l,p);return p}
async function request(chunk,l){const sig=l+'|'+chunk.join('\u241f');if(inflight.has(sig))return inflight.get(sig);const p=(async()=>{const c=window.GYX_CONFIG;if(!c?.url||!c?.publishableKey)return false;const r=await nativeFetch(c.url+'/functions/v1/translate-ui',{method:'POST',headers:{'content-type':'application/json',apikey:c.publishableKey},body:JSON.stringify({locale:l,texts:chunk})});if(!r.ok)return false;const j=await r.json();let changed=false;for(const x of j.translations||[]){const s=String(x.source_text||'').trim(),t=String(x.translated_text||'');if(s&&t){write(l,s,t);changed=true}}return changed})().finally(()=>inflight.delete(sig));inflight.set(sig,p);return p}
function fill(arr,l){const u=[...new Set(arr.map(x=>String(x||'').trim()).filter(meaningful).filter(x=>!read(l,x)))];for(let i=0;i<u.length;i+=6){request(u.slice(i,i+6),l).then(changed=>{if(changed&&current===l)schedule(30)}).catch(()=>{})}}
function apply(root=document.body,l=current){if(!root)return;const my=++seq;controls(l);if(l==='zh-CN'){restore(root);return}const j=collect(root),missing=[];for(const x of j.texts){const k=String(x.s||'').trim(),v=read(l,k);if(v&&x.n.isConnected){rendered.set(x.n,v);x.n.nodeValue=String(x.s).replace(k,v)}else if(k)missing.push(k)}for(const x of j.attrs){const k=String(x.s||'').trim(),v=read(l,k);if(v&&x.el.isConnected)x.el.setAttribute(x.a,String(x.s).replace(k,v));else if(k)missing.push(k)}if(my!==seq||l!==current)return;if(missing.length)fill(missing,l);if(bundle.get(l)!=='done'){loadBundle(l).then(loaded=>{if(loaded&&current===l)schedule(20)}).catch(()=>{})}}
function schedule(d=80){clearTimeout(timer);timer=setTimeout(()=>apply(document.body,current),d)}
async function profile(l){try{const db=window.gyxSupabase,u=await window.gyxGetVerifiedUser?.();if(db&&u){await db.from('profiles').update({locale:l,updated_at:new Date().toISOString()}).eq('user_id',u.id);try{await db.auth.updateUser({data:{locale:l}})}catch{}}}catch{}}
function set(l,{sync=true}={}){if(!VALID.has(l))return;current=l;try{localStorage.setItem(KEY,l)}catch{}controls(l);apply(document.body,l);window.dispatchEvent(new CustomEvent('gyx:localechange',{detail:{locale:l}}));window.dispatchEvent(new CustomEvent('gyx:languagechange',{detail:{locale:l}}));if(sync)profile(l)}
function patchFetch(){if(window.__GYX_LOCALE_FETCH_PATCHED)return;window.__GYX_LOCALE_FETCH_PATCHED=true;window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||'');let ni=init;if(url.includes('/functions/v1/knowledge-decision-ai')&&init?.body&&current!=='zh-CN'){try{const b=JSON.parse(String(init.body));if(b&&['final','select'].includes(b.action)){b.language=current==='zh-CN'?'zh':current;ni={...init,body:JSON.stringify(b)}}catch{}}return nativeFetch(input,ni)}}
function bind(){document.addEventListener('change',e=>{const s=e.target.closest?.('[data-language-select]');if(s&&VALID.has(s.value))set(s.value)});document.addEventListener('click',e=>{const b=e.target.closest?.('[data-set-lang],[data-lang]');const l=b?.dataset?.setLang||b?.dataset?.lang;if(VALID.has(l)){e.preventDefault();e.stopPropagation();set(l);document.querySelector('[data-lang-menu]')?.classList.add('hidden')}});window.addEventListener('storage',e=>{if(e.key===KEY&&VALID.has(e.newValue)){current=e.newValue;apply(document.body,current)}});const mo=new MutationObserver(ms=>{let ch=false;for(const m of ms){if(m.type==='characterData'){const n=m.target,p=n.parentElement;if(!p||skipped(p))continue;const v=String(n.nodeValue||'');if(rendered.get(n)===v)continue;srcText.set(n,v);ch=true}else if(m.type==='childList'){for(const n of m.addedNodes)if(n.nodeType===3&&n.parentElement&&!skipped(n.parentElement))srcText.set(n,String(n.nodeValue||''));ch=true}else if(m.type==='attributes'){const el=m.target;if(skipped(el))continue;amap(el)[m.attributeName]=el.getAttribute(m.attributeName)||'';ch=true}}if(ch)schedule()});mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']})}
function init(){current=get();patchFetch();bind();controls(current);apply(document.body,current);window.addEventListener('online',()=>schedule(30));window.addEventListener('gyx:raw-result-ready',()=>schedule(20));window.addEventListener('gyx:result-ready',()=>schedule(20))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.GYXLocale={get:()=>current,set,apply:()=>apply(document.body,current),preload:(l)=>loadBundle(l,{force:true})};
})();