(()=>{'use strict';
const db=window.gyxSupabase,I=window.GYXI18N;if(!db||!I)return;
const $=id=>document.getElementById(id),t=(k,v)=>I.t(k,v);
let user=null,favorites=[],favoriteAnswers=new Map(),materials=[],editingMaterialId=null;
const localeDb=()=>I.locale==='zh'?'zh-CN':I.locale;

function msg(id,text,kind='error'){const e=$(id);if(!e)return;e.textContent=text;e.className=`form-message show ${kind}`}
function clear(id){const e=$(id);if(e){e.textContent='';e.className='form-message'}}
function toast(text,error=false){const e=$('toast');if(!e)return;e.textContent=text;e.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.className='toast',2200)}
function err(error){const c=String(error?.code||error?.message||'').toUpperCase();if(c.includes('AUTH')||c.includes('SESSION')||c.includes('JWT'))return t('errorAuth');if(c.includes('FETCH')||c.includes('NETWORK'))return t('errorNetwork');return t('errorGeneric')}
function fmt(v){if(!v)return'—';try{return new Intl.DateTimeFormat(I.locale==='zh'?'zh-CN':I.locale==='km'?'km-KH':'en-US',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return String(v)}}
const price=v=>Number.isFinite(Number(v))?Number(v).toFixed(2):'0.00';
async function requireUser(){user=await window.gyxGetVerifiedUser?.();if(user)return true;location.replace('login.html?next='+encodeURIComponent('member.html'+(location.hash||'')));return false}
function publishCounts(){window.GYX_MEMBER_COUNTS={...(window.GYX_MEMBER_COUNTS||{}),favorites:favorites.length,materials:materials.length};window.dispatchEvent(new CustomEvent('gyx:member-counts',{detail:{...window.GYX_MEMBER_COUNTS}}))}
function favTitle(x){const a=favoriteAnswers.get(Number(x.answer_id));return I.locale==='en'?(a?.title_en||a?.title||x.matched_title):I.locale==='km'?(a?.title_km||a?.title||x.matched_title):(a?.title||x.matched_title)}
function favSummary(x){const a=favoriteAnswers.get(Number(x.answer_id));return I.locale==='en'?(a?.answer_summary_en||a?.answer_summary||x.matched_summary):I.locale==='km'?(a?.answer_summary_km||a?.answer_summary||x.matched_summary):(a?.answer_summary||x.matched_summary)}
function favoriteCheckout(item){if(String(item?.product_id||'')==='business-growth'){const api=window.GYX_GROWTH_FAVORITE;if(!api?.openProfileByFavorite){toast(window.GYXI18N.t("memberCopy001"),true);return}api.openProfileByFavorite(String(item.id));return}const tier=['essential','standard','professional','custom'].includes(String(item.tier||''))?String(item.tier):'standard',productId=item.product_id||({essential:'answer-essential',standard:'answer-standard',professional:'answer-professional',custom:'answer-custom'}[tier]||'answer-standard'),match={question:item.question||'',selections:Array.isArray(item.selections)?item.selections:[],tier,answer:{id:Number(item.answer_id),title:favTitle(item),answer_summary:favSummary(item)||'',keywords:[]}};if(!Number.isFinite(match.answer.id)||!window.GYX_ORDER?.create){toast(window.GYXI18N.t("memberCopy001"),true);return}window.GYX_ORDER.create(productId,match)}
function closeFavoriteView(){document.getElementById('gyxFavoriteViewModal')?.remove();document.body.classList.remove('modal-open');document.body.style.overflow=''}
function openFavoriteView(item){if(String(item?.product_id||'')==='business-growth'){const api=window.GYX_GROWTH_FAVORITE;if(!api?.openProfileByFavorite){toast(window.GYXI18N.t("memberCopy002"),true);return}api.openProfileByFavorite(String(item.id));return}closeFavoriteView();const m=document.createElement('div');m.id='gyxFavoriteViewModal';m.className='modal show open';m.setAttribute('aria-hidden','false');const selections=(Array.isArray(item.selections)?item.selections:[]).filter(x=>String(x||'').trim()).map(x=>`<span style="display:inline-block;margin:4px 6px 4px 0;padding:6px 9px;border-radius:999px;background:rgba(120,130,150,.12)">${String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}</span>`).join('');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));m.innerHTML=`<div class="modal-card" style="max-height:84vh;overflow:auto"><div class="modal-head"><div><h2>${esc(favTitle(item)||window.GYXI18N.t("memberCopy003"))}</h2></div><button class="icon-btn" type="button" data-favorite-close>✕</button></div><div class="form-stack"><p class="material-preview">${esc(favSummary(item)||'')}</p>${item.question?`<p class="favorite-question">“${esc(item.question)}”</p>`:''}${selections?`<div>${selections}</div>`:''}<button class="btn" type="button" data-favorite-next>${window.GYXI18N.t("memberCopy004")}</button></div></div>`;document.body.appendChild(m);document.body.classList.add('modal-open');document.body.style.overflow='hidden';m.querySelector('[data-favorite-close]').onclick=closeFavoriteView;m.addEventListener('click',e=>{if(e.target===m)closeFavoriteView()});m.querySelector('[data-favorite-next]').onclick=()=>{closeFavoriteView();favoriteCheckout(item)}}
function ensureFavoriteBulk(){const sec=$('favorites'),list=$('favoriteList');if(!sec||!list)return;let bar=$('gyxFavBulk');if(!bar){const body=sec.querySelector(':scope>.member-fold-body')||sec;bar=document.createElement('div');bar.id='gyxFavBulk';bar.className='member-search-bulk';body.insertBefore(bar,list)}bar.innerHTML=`<span>${window.GYXI18N.t("memberCopy005",{v1:favorites.length})}</span><button id="gyxFavDeleteAll" class="btn btn-danger btn-small" type="button" ${favorites.length?'':'disabled'}>${window.GYXI18N.t("memberCopy006")}</button>`;$('gyxFavDeleteAll')?.addEventListener('click',deleteAllFavorites)}
async function deleteAllFavorites(){if(!user||!favorites.length)return;if(!confirm(window.GYXI18N.t("memberCopy007",{v1:favorites.length})))return;const b=$('gyxFavDeleteAll');if(b)b.disabled=true;const r=await db.from('answer_favorites').delete().eq('user_id',user.id).select('id');if(r.error){toast(err(r.error),true);if(b)b.disabled=false;return}const n=(r.data||[]).length;favorites=[];renderFavorites();toast(window.GYXI18N.t("memberCopy008",{v1:n}))}
async function loadFavorites(){clear('favoritesMessage');const list=$('favoriteList');if(!list)return;list.innerHTML=`<div class="loading-card">${t('loading')}</div>`;const r=await db.from('answer_favorites').select('id,user_id,answer_id,question,selections,tier,product_id,quoted_price,matched_title,matched_summary,created_at,updated_at').eq('user_id',user.id).order('updated_at',{ascending:false});if(r.error){msg('favoritesMessage',err(r.error));list.replaceChildren();return}favorites=r.data||[];favoriteAnswers=new Map();const ids=[...new Set(favorites.map(x=>Number(x.answer_id)).filter(Number.isFinite))];if(ids.length){const a=await db.from('product_answer_options').select('id,title,title_en,title_km,answer_summary,answer_summary_en,answer_summary_km').in('id',ids);(a.data||[]).forEach(x=>favoriteAnswers.set(Number(x.id),x))}renderFavorites()}
function renderFavorites(){const list=$('favoriteList');if(!list)return;list.replaceChildren();ensureFavoriteBulk();if(!favorites.length){const e=document.createElement('div');e.className='empty-state';e.textContent=t('noFavorites');list.append(e);publishCounts();return}favorites.forEach(item=>{const growth=String(item.product_id||'')==='business-growth',card=document.createElement('article');card.className='favorite-card';card.dataset.favoriteId=String(item.id);const top=document.createElement('div');top.className='favorite-card-top';const h=document.createElement('h3');h.textContent=favTitle(item);const p=document.createElement('strong');p.className='favorite-price';p.textContent=growth?window.GYXI18N.t("memberCopy009"):price(item.quoted_price)+' USDT';top.append(h,p);const summary=document.createElement('p');summary.className='material-preview';summary.textContent=growth?window.GYXI18N.t("memberCopy010"):(favSummary(item)||'');const actions=document.createElement('div');actions.className='material-actions';const view=document.createElement('button');view.className='btn btn-secondary btn-small';view.type='button';view.dataset.favAction='view';view.dataset.favoriteId=String(item.id);view.textContent=growth?window.GYXI18N.t("memberCopy011"):window.GYXI18N.t("memberCopy012");view.onclick=()=>openFavoriteView(item);const remove=document.createElement('button');remove.className='btn btn-danger btn-small';remove.type='button';remove.dataset.favAction='remove';remove.dataset.favoriteId=String(item.id);remove.textContent=t('removeFavorite');remove.onclick=()=>deleteFavorite(item.id);actions.append(view,remove);card.append(top,summary);if(!growth){const q=document.createElement('p');q.className='favorite-question';q.textContent='“'+String(item.question||'')+'”';const chips=document.createElement('div');chips.className='favorite-choices';(Array.isArray(item.selections)?item.selections:[]).forEach(s=>{const x=document.createElement('span');x.textContent=s;chips.append(x)});card.append(q,chips)}card.append(actions);list.append(card)});publishCounts()}
async function deleteFavorite(id){if(!confirm(t('confirmRemoveFavorite')))return;const r=await db.from('answer_favorites').delete().eq('id',id).eq('user_id',user.id).select('id').maybeSingle();if(r.error||!r.data?.id){msg('favoritesMessage',err(r.error));return}favorites=favorites.filter(x=>String(x.id)!==String(id));renderFavorites()}
async function loadMaterials(){const r=await db.from('member_materials').select('id,user_id,title,category,language,content,source_name,created_at,updated_at').eq('user_id',user.id).order('updated_at',{ascending:false});if(r.error){msg('materialMessage',err(r.error));return}materials=r.data||[];renderMaterials()}
function category(c){return t({work:'catWork',creation:'catCreation',business:'catBusiness',automation:'catAutomation',other:'all'}[c]||'all')}
function renderMaterials(){const list=$('materialList');if(!list)return;const q=String($('materialSearch')?.value||'').trim().toLowerCase(),rows=materials.filter(x=>!q||`${x.title} ${x.content} ${x.source_name||''}`.toLowerCase().includes(q));list.replaceChildren();if(!rows.length){const e=document.createElement('div');e.className='empty-state';e.textContent=t('noMaterials');list.append(e);publishCounts();return}rows.forEach(item=>{const card=document.createElement('article');card.className='material-card';const top=document.createElement('div');top.className='material-top';const wrap=document.createElement('div'),h=document.createElement('h3'),meta=document.createElement('p');h.className='material-title';h.textContent=item.title;meta.className='order-number';meta.textContent=`${category(item.category)} · ${item.language} · ${fmt(item.updated_at)}`;wrap.append(h,meta);const badge=document.createElement('span');badge.className='status-badge paid';badge.textContent=t('privateMaterial');top.append(wrap,badge);const pre=document.createElement('p');pre.className='material-preview';pre.textContent=item.content;const actions=document.createElement('div');actions.className='material-actions';const edit=document.createElement('button'),del=document.createElement('button');edit.className='btn btn-secondary btn-small';edit.type='button';edit.textContent=t('edit');edit.onclick=()=>editMaterial(item.id);del.className='btn btn-danger btn-small';del.type='button';del.textContent=t('delete');del.onclick=()=>deleteMaterial(item.id);actions.append(edit,del);card.append(top,pre,actions);list.append(card)});publishCounts()}
function resetMaterial(){editingMaterialId=null;$('materialForm')?.reset();if($('materialCategory'))$('materialCategory').value='work';if($('materialLanguage'))$('materialLanguage').value=localeDb();if($('saveMaterialButton'))$('saveMaterialButton').textContent=t('saveMaterial');if($('materialLength'))$('materialLength').textContent='0 / 50,000';clear('materialMessage')}
function editMaterial(id){const x=materials.find(r=>r.id===id);if(!x)return;editingMaterialId=id;$('materialTitle').value=x.title;$('materialSource').value=x.source_name||'';$('materialCategory').value=x.category;$('materialLanguage').value=x.language;$('materialContent').value=x.content;$('materialLength').textContent=`${x.content.length.toLocaleString()} / 50,000`;$('saveMaterialButton').textContent=t('updateMaterial');$('materialForm').scrollIntoView({behavior:'smooth',block:'start'})}
async function saveMaterial(e){e.preventDefault();clear('materialMessage');const title=$('materialTitle').value.trim(),content=$('materialContent').value.trim();if(title.length<2||content.length<10){msg('materialMessage',t('errorGeneric'));return}const payload={title,category:$('materialCategory').value,language:$('materialLanguage').value,content,source_name:$('materialSource').value.trim()||null},b=$('saveMaterialButton');b.disabled=true;b.textContent=t('saving');const r=editingMaterialId?await db.from('member_materials').update(payload).eq('id',editingMaterialId).eq('user_id',user.id).select('id').single():await db.from('member_materials').insert({...payload,user_id:user.id}).select('id').single();b.disabled=false;b.textContent=t(editingMaterialId?'updateMaterial':'saveMaterial');if(r.error){msg('materialMessage',err(r.error));return}resetMaterial();toast(t('saved'));await loadMaterials()}
async function deleteMaterial(id){if(!confirm(t('confirmDelete')))return;const r=await db.from('member_materials').delete().eq('id',id).eq('user_id',user.id);if(r.error){msg('materialMessage',err(r.error));return}if(editingMaterialId===id)resetMaterial();await loadMaterials()}
function bind(){const form=$('materialForm'),n=$('newMaterialButton'),c=$('materialContent'),s=$('materialSearch');form?.addEventListener('submit',saveMaterial);n?.addEventListener('click',()=>{resetMaterial();$('materialTitle')?.focus()});c?.addEventListener('input',()=>{if($('materialLength'))$('materialLength').textContent=`${c.value.length.toLocaleString()} / 50,000`});s?.addEventListener('input',renderMaterials)}
async function init(){bind();if(!(await requireUser()))return;if($('materialLanguage'))$('materialLanguage').value=localeDb();await Promise.all([loadFavorites(),loadMaterials()]);window.addEventListener('gyx:languagechange',()=>{renderFavorites();renderMaterials()})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();