(()=>{'use strict';
const $=id=>document.getElementById(id);let savedKey='',saving=false,enhancedKey='';
function currentKey(){const m=window.GYX_CURRENT_AI_MATCH;if(!m)return'';return[m.question,(m.selections||[]).join('|'),m.answer?.id||''].join('::')}
function resetFreshHome(){const input=$('problemInput'),quiz=$('quizPanel'),result=$('resultPanel'),msg=$('problemMessage');if(input){input.value='';input.blur()}quiz?.classList.add('hidden');result?.classList.add('hidden');if(msg){msg.textContent='';msg.className='form-message'}window.GYX_CURRENT_AI_MATCH=null;window.GYX_TRANSLATED_DISPLAY=null}
function enhance(){const R=$('resultPanel');if(!R||R.classList.contains('hidden'))return;const m=window.GYX_CURRENT_AI_MATCH;if(!m)return;const k=currentKey();if(k!==enhancedKey){const order=$('orderAnswerButton');if(order&&!order.dataset.gyxPremiumStyled){order.dataset.gyxPremiumStyled='1';order.textContent='点击下单获取您的方案';order.style.borderRadius='18px';order.style.minHeight='56px';order.style.fontWeight='800';order.style.letterSpacing='.02em';order.style.boxShadow='0 10px 28px rgba(55,92,255,.22)'}enhancedKey=k}}
async function saveExplicit(){const m=window.GYX_CURRENT_AI_MATCH;if(!m||saving)return false;let u;try{u=await window.gyxGetVerifiedUser?.()}catch{}if(!u)return false;const key=[u.id,currentKey()].join('::');if(key===savedKey)return true;saving=true;const payload={question:m.question||'',selections:Array.isArray(m.selections)?m.selections:[],matched_answer_id:Number.isFinite(Number(m.answer?.id))?Number(m.answer.id):null,matched_title:m.answer?.title||m.delivery_package?.title||m.question||'',matched_summary:m.answer?.answer_summary||m.delivery_package?.summary||'',tier:m.tier||'essential',confidence:Number(m.confidence||0)};try{const r=await window.gyxInvokeFunction?.('save-search-history',payload);if(r?.ok){savedKey=key;return true}return false}catch{return false}finally{saving=false}}
window.gyxSaveCurrentSearchHistory=saveExplicit;
function tryEnhance(retries=12){enhance();if(!window.GYX_CURRENT_AI_MATCH&&retries>0)setTimeout(()=>tryEnhance(retries-1),120)}
const R=$('resultPanel');if(R)new MutationObserver(ms=>{if(ms.some(m=>m.type==='attributes'&&m.attributeName==='class'))tryEnhance()}).observe(R,{attributes:true,attributeFilter:['class']});
function boot(){resetFreshHome();setTimeout(()=>{resetFreshHome();tryEnhance()},220)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.addEventListener('pageshow',()=>resetFreshHome());
})();