(() => {
  'use strict';
  const currentPath=(window.location.pathname||'').toLowerCase(),search=window.location.search||'',hash=window.location.hash||'',recoveryLink=/(?:[?&#])(type=recovery|token_hash=|access_token=|refresh_token=|code=)/i.test(search+hash),paymentRef=currentPath.endsWith('/member.html')?new URLSearchParams(search).get('pay'):'';
  if(paymentRef){document.documentElement.classList.add('payment-entry');const s=document.createElement('style');s.id='payment-entry-guard';s.textContent='html.payment-entry,html.payment-entry body{background:var(--bg,#f4f8ff)!important}html.payment-entry .site-header,html.payment-entry main,html.payment-entry .mobile-bottom-nav,html.payment-entry #supportPanel{display:none!important}#memberPaymentScreen.gyx-entry-shell{position:fixed;inset:0;z-index:300000;background:var(--bg,#f4f8ff);overflow:auto;color:var(--text,#17324d)}#memberPaymentScreen.gyx-entry-shell .gyx-entry-inner{width:min(100%,680px);margin:0 auto;padding:18px 14px 40px}#memberPaymentScreen.gyx-entry-shell h2{margin:6px 0 18px;font-size:26px}#memberPaymentScreen.gyx-entry-shell .gyx-entry-bar{height:18px;border-radius:9px;background:rgba(127,150,180,.14);margin:12px 0}#memberPaymentScreen.gyx-entry-shell .gyx-entry-bar.big{height:46px;width:52%}html[data-theme="dark"] #memberPaymentScreen.gyx-entry-shell{background:#071321}';document.head.appendChild(s);const mount=()=>{if(document.getElementById('memberPaymentScreen'))return;const h=document.createElement('section');h.id='memberPaymentScreen';h.className='gyx-pay-ui gyx-pay-full gyx-entry-shell';const raw=String(localStorage.getItem('lang')||document.documentElement.lang||'zh').toLowerCase(),title=raw.startsWith('en')?'Complete payment':raw.startsWith('km')?'បញ្ចប់ការទូទាត់':'完成付款';h.innerHTML='<div class="gyx-entry-inner"><h2>'+title+'</h2><div class="gyx-entry-bar"></div><div class="gyx-entry-bar big"></div><div class="gyx-entry-bar"></div><div class="gyx-entry-bar"></div></div>';document.body.appendChild(h)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount()}
  if(!currentPath.includes('reset-password')&&recoveryLink){const target=new URL('reset-password.html',window.location.href);target.search=search;target.hash=hash;window.location.replace(target.toString());return}
  const config=Object.freeze({url:'https://afzcohtnljnmucrkgcaz.supabase.co',publishableKey:'sb_publishable_EqF-kTNRsSZWhUE8LWB8DQ_UNkTjImv',wallet:'TKfQoN7kZirALGYxMkxU4SoqMWJRqXsh7k',network:'USDT-TRC20',support:'@qqyousubot'});window.GYX_CONFIG=config;
  if(!window.supabase||typeof window.supabase.createClient!=='function'){console.error('Supabase client library failed to load. Search configuration remains available.');return}
  const client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'implicit'}});
  let verifiedUser=null,verifiedAt=0,verifiedPromise=null;
  function markKnownMember(){try{localStorage.setItem('gyx_known_member','1')}catch{}}
  function isKnownMember(){try{return localStorage.getItem('gyx_known_member')==='1'}catch{return false}}
  function safeNext(value,fallback='member.html'){if(!value)return fallback;try{const decoded=decodeURIComponent(String(value)),target=new URL(decoded,window.location.href);if(target.origin!==window.location.origin)return fallback;const filename=target.pathname.split('/').pop()||'',allowed=new Set(['shop.html','member.html','index.html','community.html']);if(!allowed.has(filename))return fallback;return filename+target.search+target.hash}catch{return fallback}}
  function authEntryUrl(next='shop.html'){const target=safeNext(next,'shop.html'),mode=isKnownMember()?'login':'register';return `login.html?mode=${mode}&next=${encodeURIComponent(target)}`}
  async function getVerifiedUser(force=false){
    const now=Date.now();
    if(!force&&verifiedUser&&now-verifiedAt<60000)return verifiedUser;
    if(!force&&verifiedPromise)return verifiedPromise;
    verifiedPromise=(async()=>{try{const {data:sessionData}=await client.auth.getSession(),sessionUser=sessionData?.session?.user||null;if(!sessionUser){verifiedUser=null;verifiedAt=Date.now();return null}markKnownMember();verifiedUser=sessionUser;verifiedAt=Date.now();if(!force){client.auth.getUser().then(({data,error})=>{if(!error&&data?.user){markKnownMember();verifiedUser=data.user;verifiedAt=Date.now()}}).catch(()=>{});return verifiedUser}try{const {data,error}=await client.auth.getUser();if(!error&&data?.user){markKnownMember();verifiedUser=data.user;verifiedAt=Date.now();return verifiedUser}}catch{}return verifiedUser}catch{verifiedUser=null;verifiedAt=Date.now();return null}})();
    try{return await verifiedPromise}finally{verifiedPromise=null}
  }
  client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){verifiedUser=null;verifiedAt=0;verifiedPromise=null;return}if(session?.user){markKnownMember();verifiedUser=session.user;verifiedAt=Date.now()}});
  async function invokeFunction(name,body){const {data,error}=await client.functions.invoke(name,{body});if(!error)return data;let code='';try{const payload=await error.context?.clone?.().json();code=payload?.error||payload?.message||''}catch{}const wrapped=new Error(code||error.message||'FUNCTION_REQUEST_FAILED');wrapped.code=code||'FUNCTION_REQUEST_FAILED';throw wrapped}
  window.gyxSupabase=client;window.gyxGetVerifiedUser=getVerifiedUser;window.gyxSafeNext=safeNext;window.gyxInvokeFunction=invokeFunction;window.gyxIsKnownMember=isKnownMember;window.gyxAuthEntryUrl=authEntryUrl;
  if(currentPath.endsWith('/community.html'))setTimeout(()=>{getVerifiedUser().then(u=>{if(!u)location.replace(authEntryUrl('community.html'))}).catch(()=>location.replace(authEntryUrl('community.html')))},0);
})();