X = {
'赚钱':'money income earn','副业':'side income freelance','兼职':'part time freelance','收入':'income salary','被动收入':'passive income','理财':'personal finance investing budget',
'投资':'investing investment','股票':'stock','基金':'fund index','储蓄':'saving','存钱':'saving budget','预算':'budget','退休':'retirement','养老金':'pension retirement',
'贷款':'loan','信用卡':'credit card','债务':'debt','税':'tax','报税':'tax return','保险':'insurance','房贷':'mortgage','买房':'buying house mortgage','租房':'rent',
'工资':'salary','加薪':'raise salary','跳槽':'job change','面试':'interview','简历':'resume','求职':'job search','辞职':'resign quit','老板':'boss manager','同事':'coworker',
'职场':'workplace career','升职':'promotion','绩效':'performance review','远程':'remote','加班':'overtime','裁员':'layoff','自由职业':'freelancing freelancer','接单':'client freelance',
'客户':'client customer','报价':'quote rate pricing','定价':'pricing price','合同':'contract','发票':'invoice','外包':'outsourcing','网站':'website','建站':'website wordpress',
'域名':'domain','服务器':'server hosting','流量':'traffic','seo':'seo','搜索引擎':'search engine seo','谷歌':'google','广告':'advertising ad adsense','联盟营销':'affiliate',
'电商':'ecommerce online store','网店':'online store ecommerce','店铺':'store shop','亚马逊':'amazon','支付':'payment','用户体验':'user experience ux','设计':'design',
'平面设计':'graphic design','logo':'logo','品牌':'brand branding','营销':'marketing','推广':'promotion marketing','社交媒体':'social media','视频':'video','剪辑':'video editing',
'拍摄':'shooting camera','摄影':'photography photo','音频':'audio','播客':'podcast','直播':'live streaming','写作':'writing','博客':'blog','电子书':'ebook','出版':'publishing',
'版权':'copyright','商标':'trademark','法律':'law legal','公司':'company business','创业':'startup business','注册公司':'company registration llc','老板':'owner manager',
'管理':'management','项目管理':'project management','团队':'team','会议':'meeting','人工智能':'artificial intelligence ai','机器学习':'machine learning','模型':'model',
'聊天机器人':'chatbot','提示词':'prompt','自动化':'automation','软件':'software','工具':'tool','经济':'economics economy','通货膨胀':'inflation','利率':'interest rate',
'汇率':'exchange rate currency','比特币':'bitcoin','加密货币':'cryptocurrency','手工':'craft handmade','做菜':'cooking','餐厅':'restaurant','外卖':'delivery food',
'移民':'immigration expat','出国':'abroad expat','签证':'visa','海外':'overseas expat','开源':'open source','数据':'data','分析':'analysis analytics','量化':'quantitative trading',
'交易':'trading trade','期权':'option','产品经理':'product manager','需求':'requirement','用户':'user','转化率':'conversion rate','邮件':'email','订阅':'subscription',
'会员':'membership subscription','课程':'course','教学':'teaching course','翻译':'translation','变现':'monetize monetization','小红书':'social media content creator',
'抖音':'tiktok short video','自媒体':'content creator blog youtube','youtube':'youtube','公众号':'blog newsletter','私域':'customer community email list',
}
