alter table public.admin_panel_pin_locks
  add column if not exists attempt_session_id text,
  add column if not exists is_locked boolean not null default false,
  add column if not exists password_changed_at timestamptz;

update public.admin_panel_pin_locks
set is_locked = false,
    failed_attempts = least(greatest(coalesce(failed_attempts,0),0),6),
    locked_until = null
where true;

create table if not exists public.admin_panel_pin_audit (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null,
  event_type text not null check (event_type in ('pin_set','unlock_success','unlock_failure','session_locked','pin_changed')),
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.admin_panel_pin_audit enable row level security;
revoke all on table public.admin_panel_pin_audit from anon, authenticated;
revoke all on table public.admin_panel_pin_locks from anon, authenticated;

create index if not exists admin_panel_pin_audit_admin_time_idx
  on public.admin_panel_pin_audit(admin_user_id, created_at desc);

create index if not exists admin_panel_pin_audit_event_time_idx
  on public.admin_panel_pin_audit(event_type, created_at desc);
