create table if not exists public.site_visitor_locations (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  latitude double precision null,
  longitude double precision null,
  accuracy_m double precision null,
  locality text null,
  city text null,
  region text null,
  country text null,
  country_code text null,
  postcode text null,
  source text not null check (source in ('gps','ip')),
  consent_status text not null,
  page_path text null,
  created_at timestamptz not null default now()
);
alter table public.site_visitor_locations enable row level security;
revoke all on table public.site_visitor_locations from public, anon, authenticated;
grant insert on table public.site_visitor_locations to anon, authenticated;
grant select, insert, update, delete on table public.site_visitor_locations to service_role;
grant usage, select on sequence public.site_visitor_locations_id_seq to anon, authenticated, service_role;
drop policy if exists site_visitor_locations_anon_insert on public.site_visitor_locations;
create policy site_visitor_locations_anon_insert on public.site_visitor_locations for insert to anon with check (user_id is null);
drop policy if exists site_visitor_locations_authenticated_insert on public.site_visitor_locations;
create policy site_visitor_locations_authenticated_insert on public.site_visitor_locations for insert to authenticated with check (user_id is null or user_id = (select auth.uid()));
create index if not exists site_visitor_locations_created_at_idx on public.site_visitor_locations(created_at desc);
create index if not exists site_visitor_locations_user_id_idx on public.site_visitor_locations(user_id) where user_id is not null;
create index if not exists site_visitor_locations_country_city_idx on public.site_visitor_locations(country_code, city);
